# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Calibration.ui'
#
# Created: Mon Jun  9 19:38:59 2014
# by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui


class Ui_XrsCalibrationWidget(object):
    def setupUi(self, XrsCalibrationWidget):
        XrsCalibrationWidget.setObjectName("XrsCalibrationWidget")
        XrsCalibrationWidget.resize(1131, 699)
        XrsCalibrationWidget.setMinimumSize(QtCore.QSize(5, 5))
        XrsCalibrationWidget.setStyleSheet("")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(XrsCalibrationWidget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.splitter = QtGui.QSplitter(XrsCalibrationWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tab_widget = QtGui.QTabWidget(self.layoutWidget)
        self.tab_widget.setObjectName("tab_widget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.img_pg_layout = GraphicsLayoutWidget(self.tab)
        self.img_pg_layout.setMinimumSize(QtCore.QSize(5, 5))
        self.img_pg_layout.setFrameShape(QtGui.QFrame.NoFrame)
        self.img_pg_layout.setFrameShadow(QtGui.QFrame.Plain)
        self.img_pg_layout.setObjectName("img_pg_layout")
        self.horizontalLayout_2.addWidget(self.img_pg_layout)
        self.tab_widget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cake_pg_layout = GraphicsLayoutWidget(self.tab_2)
        self.cake_pg_layout.setObjectName("cake_pg_layout")
        self.horizontalLayout_3.addWidget(self.cake_pg_layout)
        self.tab_widget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.tab_3)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.spectrum_pg_layout = GraphicsLayoutWidget(self.tab_3)
        self.spectrum_pg_layout.setMinimumSize(QtCore.QSize(5, 5))
        self.spectrum_pg_layout.setSizeIncrement(QtCore.QSize(5, 5))
        self.spectrum_pg_layout.setBaseSize(QtCore.QSize(5, 5))
        self.spectrum_pg_layout.setObjectName("spectrum_pg_layout")
        self.horizontalLayout_7.addWidget(self.spectrum_pg_layout)
        self.tab_widget.addTab(self.tab_3, "")
        self.verticalLayout_2.addWidget(self.tab_widget)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.integrate_btn = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.integrate_btn.sizePolicy().hasHeightForWidth())
        self.integrate_btn.setSizePolicy(sizePolicy)
        self.integrate_btn.setMinimumSize(QtCore.QSize(140, 0))
        self.integrate_btn.setFlat(True)
        self.integrate_btn.setObjectName("integrate_btn")
        self.horizontalLayout_4.addWidget(self.integrate_btn)
        self.refine_btn = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refine_btn.sizePolicy().hasHeightForWidth())
        self.refine_btn.setSizePolicy(sizePolicy)
        self.refine_btn.setMinimumSize(QtCore.QSize(140, 0))
        self.refine_btn.setFlat(True)
        self.refine_btn.setObjectName("refine_btn")
        self.horizontalLayout_4.addWidget(self.refine_btn)
        spacerItem = QtGui.QSpacerItem(168, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.pos_lbl = QtGui.QLabel(self.layoutWidget)
        self.pos_lbl.setObjectName("pos_lbl")
        self.horizontalLayout_4.addWidget(self.pos_lbl)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.widget = QtGui.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.load_img_btn = QtGui.QPushButton(self.widget)
        self.load_img_btn.setMaximumSize(QtCore.QSize(1677215, 16777215))
        self.load_img_btn.setFlat(True)
        self.load_img_btn.setObjectName("load_img_btn")
        self.horizontalLayout_5.addWidget(self.load_img_btn)
        self.load_previous_img_btn = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_previous_img_btn.sizePolicy().hasHeightForWidth())
        self.load_previous_img_btn.setSizePolicy(sizePolicy)
        self.load_previous_img_btn.setMinimumSize(QtCore.QSize(50, 0))
        self.load_previous_img_btn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.load_previous_img_btn.setFlat(True)
        self.load_previous_img_btn.setObjectName("load_previous_img_btn")
        self.horizontalLayout_5.addWidget(self.load_previous_img_btn)
        self.load_next_img_btn = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_next_img_btn.sizePolicy().hasHeightForWidth())
        self.load_next_img_btn.setSizePolicy(sizePolicy)
        self.load_next_img_btn.setMinimumSize(QtCore.QSize(50, 0))
        self.load_next_img_btn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.load_next_img_btn.setFlat(True)
        self.load_next_img_btn.setObjectName("load_next_img_btn")
        self.horizontalLayout_5.addWidget(self.load_next_img_btn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.filename_lbl = QtGui.QLabel(self.widget)
        self.filename_lbl.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.filename_lbl.setObjectName("filename_lbl")
        self.verticalLayout_3.addWidget(self.filename_lbl)
        self.ToolBox = QtGui.QToolBox(self.widget)
        self.ToolBox.setEnabled(True)
        self.ToolBox.setMinimumSize(QtCore.QSize(280, 0))
        self.ToolBox.setObjectName("ToolBox")
        self.start_values = QtGui.QWidget()
        self.start_values.setEnabled(True)
        self.start_values.setGeometry(QtCore.QRect(0, 0, 415, 899))
        self.start_values.setObjectName("start_values")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.start_values)
        self.verticalLayout_5.setSpacing(30)
        self.verticalLayout_5.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_2 = QtGui.QGroupBox(self.start_values)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setHorizontalSpacing(8)
        self.gridLayout.setVerticalSpacing(12)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.sv_pixel_height_txt = QtGui.QLineEdit(self.groupBox_2)
        self.sv_pixel_height_txt.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.sv_pixel_height_txt.setObjectName("sv_pixel_height_txt")
        self.gridLayout.addWidget(self.sv_pixel_height_txt, 4, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.calibrant_cb = QtGui.QComboBox(self.groupBox_2)
        self.calibrant_cb.setFocusPolicy(QtCore.Qt.NoFocus)
        self.calibrant_cb.setEditable(False)
        self.calibrant_cb.setFrame(True)
        self.calibrant_cb.setObjectName("calibrant_cb")
        self.gridLayout.addWidget(self.calibrant_cb, 6, 1, 1, 2)
        self.sv_pixel_width_txt = QtGui.QLineEdit(self.groupBox_2)
        self.sv_pixel_width_txt.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.sv_pixel_width_txt.setObjectName("sv_pixel_width_txt")
        self.gridLayout.addWidget(self.sv_pixel_width_txt, 3, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.sv_distance_txt = QtGui.QLineEdit(self.groupBox_2)
        self.sv_distance_txt.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.sv_distance_txt.setObjectName("sv_distance_txt")
        self.gridLayout.addWidget(self.sv_distance_txt, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.sv_wavelength_txt = QtGui.QLineEdit(self.groupBox_2)
        self.sv_wavelength_txt.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.sv_wavelength_txt.setObjectName("sv_wavelength_txt")
        self.gridLayout.addWidget(self.sv_wavelength_txt, 1, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 2, 1, 1)
        self.sv_polarization_txt = QtGui.QLineEdit(self.groupBox_2)
        self.sv_polarization_txt.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.sv_polarization_txt.setObjectName("sv_polarization_txt")
        self.gridLayout.addWidget(self.sv_polarization_txt, 2, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        self.label_14.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.rotate_p90_btn = QtGui.QPushButton(self.groupBox_2)
        self.rotate_p90_btn.setFlat(True)
        self.rotate_p90_btn.setObjectName("rotate_p90_btn")
        self.gridLayout_4.addWidget(self.rotate_p90_btn, 0, 0, 1, 1)
        self.rotate_m90_btn = QtGui.QPushButton(self.groupBox_2)
        self.rotate_m90_btn.setFlat(True)
        self.rotate_m90_btn.setObjectName("rotate_m90_btn")
        self.gridLayout_4.addWidget(self.rotate_m90_btn, 0, 1, 1, 1)
        self.invert_horizontal_btn = QtGui.QPushButton(self.groupBox_2)
        self.invert_horizontal_btn.setFlat(True)
        self.invert_horizontal_btn.setObjectName("invert_horizontal_btn")
        self.gridLayout_4.addWidget(self.invert_horizontal_btn, 1, 0, 1, 1)
        self.invert_vertical_btn = QtGui.QPushButton(self.groupBox_2)
        self.invert_vertical_btn.setFlat(True)
        self.invert_vertical_btn.setObjectName("invert_vertical_btn")
        self.gridLayout_4.addWidget(self.invert_vertical_btn, 1, 1, 1, 1)
        self.reset_transformations_btn = QtGui.QPushButton(self.groupBox_2)
        self.reset_transformations_btn.setFlat(True)
        self.reset_transformations_btn.setObjectName("reset_transformations_btn")
        self.gridLayout_4.addWidget(self.reset_transformations_btn, 2, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.start_values)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem1 = QtGui.QSpacerItem(78, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 2)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 1, 1, 2)
        self.peak_num_sb = QtGui.QSpinBox(self.groupBox_3)
        self.peak_num_sb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.peak_num_sb.setMinimum(1)
        self.peak_num_sb.setObjectName("peak_num_sb")
        self.gridLayout_2.addWidget(self.peak_num_sb, 0, 3, 1, 1)
        self.automatic_peak_num_inc_cb = QtGui.QCheckBox(self.groupBox_3)
        self.automatic_peak_num_inc_cb.setChecked(True)
        self.automatic_peak_num_inc_cb.setObjectName("automatic_peak_num_inc_cb")
        self.gridLayout_2.addWidget(self.automatic_peak_num_inc_cb, 1, 2, 1, 2)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.line = QtGui.QFrame(self.groupBox_3)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.automatic_peak_search_rb = QtGui.QRadioButton(self.groupBox_3)
        self.automatic_peak_search_rb.setChecked(True)
        self.automatic_peak_search_rb.setObjectName("automatic_peak_search_rb")
        self.verticalLayout_4.addWidget(self.automatic_peak_search_rb)
        self.select_peak_rb = QtGui.QRadioButton(self.groupBox_3)
        self.select_peak_rb.setObjectName("select_peak_rb")
        self.verticalLayout_4.addWidget(self.select_peak_rb)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_9.addWidget(self.label_13)
        self.search_size_sb = QtGui.QSpinBox(self.groupBox_3)
        self.search_size_sb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.search_size_sb.setMaximum(9000)
        self.search_size_sb.setProperty("value", 10)
        self.search_size_sb.setObjectName("search_size_sb")
        self.horizontalLayout_9.addWidget(self.search_size_sb)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.line_2 = QtGui.QFrame(self.groupBox_3)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_4.addWidget(self.line_2)
        self.clear_peaks_btn = QtGui.QPushButton(self.groupBox_3)
        self.clear_peaks_btn.setFlat(True)
        self.clear_peaks_btn.setObjectName("clear_peaks_btn")
        self.verticalLayout_4.addWidget(self.clear_peaks_btn)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.groupBox = QtGui.QGroupBox(self.start_values)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_5.setSpacing(9)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.options_intensity_limit_txt = QtGui.QLineEdit(self.groupBox)
        self.options_intensity_limit_txt.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.options_intensity_limit_txt.setObjectName("options_intensity_limit_txt")
        self.gridLayout_5.addWidget(self.options_intensity_limit_txt, 4, 1, 1, 1)
        self.options_num_rings_sb = QtGui.QSpinBox(self.groupBox)
        self.options_num_rings_sb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.options_num_rings_sb.setProperty("value", 15)
        self.options_num_rings_sb.setObjectName("options_num_rings_sb")
        self.gridLayout_5.addWidget(self.options_num_rings_sb, 5, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox)
        self.label_17.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 1, 0, 1, 1)
        self.label_24 = QtGui.QLabel(self.groupBox)
        self.label_24.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_5.addWidget(self.label_24, 5, 0, 1, 1)
        self.options_delta_tth_txt = QtGui.QLineEdit(self.groupBox)
        self.options_delta_tth_txt.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.options_delta_tth_txt.setObjectName("options_delta_tth_txt")
        self.gridLayout_5.addWidget(self.options_delta_tth_txt, 2, 1, 1, 1)
        self.label_23 = QtGui.QLabel(self.groupBox)
        self.label_23.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_5.addWidget(self.label_23, 4, 0, 1, 1)
        self.options_intensity_mean_factor_sb = QtGui.QDoubleSpinBox(self.groupBox)
        self.options_intensity_mean_factor_sb.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.options_intensity_mean_factor_sb.setSingleStep(1.0)
        self.options_intensity_mean_factor_sb.setProperty("value", 3.0)
        self.options_intensity_mean_factor_sb.setObjectName("options_intensity_mean_factor_sb")
        self.gridLayout_5.addWidget(self.options_intensity_mean_factor_sb, 3, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.groupBox)
        self.label_25.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_5.addWidget(self.label_25, 3, 0, 1, 1)
        self.options_peaksearch_algorithm_cb = QtGui.QComboBox(self.groupBox)
        self.options_peaksearch_algorithm_cb.setObjectName("options_peaksearch_algorithm_cb")
        self.options_peaksearch_algorithm_cb.addItem("")
        self.options_peaksearch_algorithm_cb.addItem("")
        self.gridLayout_5.addWidget(self.options_peaksearch_algorithm_cb, 1, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.groupBox)
        self.label_18.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_5.addWidget(self.label_18, 2, 0, 1, 1)
        self.options_automatic_refinement_cb = QtGui.QCheckBox(self.groupBox)
        self.options_automatic_refinement_cb.setChecked(True)
        self.options_automatic_refinement_cb.setObjectName("options_automatic_refinement_cb")
        self.gridLayout_5.addWidget(self.options_automatic_refinement_cb, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox)
        spacerItem4 = QtGui.QSpacerItem(20, 1, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.ToolBox.addItem(self.start_values, "")
        self.pyFAI = QtGui.QWidget()
        self.pyFAI.setGeometry(QtCore.QRect(0, 0, 430, 482))
        self.pyFAI.setObjectName("pyFAI")
        self.gridLayout_3 = QtGui.QGridLayout(self.pyFAI)
        self.gridLayout_3.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_3.setHorizontalSpacing(8)
        self.gridLayout_3.setVerticalSpacing(12)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_19 = QtGui.QLabel(self.pyFAI)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 1, 2, 1, 1)
        self.label_20 = QtGui.QLabel(self.pyFAI)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 0, 2, 1, 1)
        self.pf_distance_txt = QtGui.QLineEdit(self.pyFAI)
        self.pf_distance_txt.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pf_distance_txt.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.pf_distance_txt.setObjectName("pf_distance_txt")
        self.gridLayout_3.addWidget(self.pf_distance_txt, 0, 1, 1, 1)
        self.pf_wavelength_txt = QtGui.QLineEdit(self.pyFAI)
        self.pf_wavelength_txt.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.pf_wavelength_txt.setObjectName("pf_wavelength_txt")
        self.gridLayout_3.addWidget(self.pf_wavelength_txt, 1, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.pyFAI)
        self.label_22.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 1, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.pyFAI)
        self.label_21.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 0, 0, 1, 1)
        self.label_27 = QtGui.QLabel(self.pyFAI)
        self.label_27.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 3, 0, 1, 1)
        self.pf_wavelength_cb = QtGui.QCheckBox(self.pyFAI)
        self.pf_wavelength_cb.setText("")
        self.pf_wavelength_cb.setObjectName("pf_wavelength_cb")
        self.gridLayout_3.addWidget(self.pf_wavelength_cb, 1, 3, 1, 1)
        self.pf_poni1_txt = QtGui.QLineEdit(self.pyFAI)
        self.pf_poni1_txt.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.pf_poni1_txt.setObjectName("pf_poni1_txt")
        self.gridLayout_3.addWidget(self.pf_poni1_txt, 3, 1, 1, 1)
        self.label_29 = QtGui.QLabel(self.pyFAI)
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 3, 2, 1, 1)
        self.pf_poni2_txt = QtGui.QLineEdit(self.pyFAI)
        self.pf_poni2_txt.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.pf_poni2_txt.setObjectName("pf_poni2_txt")
        self.gridLayout_3.addWidget(self.pf_poni2_txt, 4, 1, 1, 1)
        self.label_30 = QtGui.QLabel(self.pyFAI)
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 4, 2, 1, 1)
        self.label_28 = QtGui.QLabel(self.pyFAI)
        self.label_28.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 5, 0, 1, 1)
        self.pf_rotation1_txt = QtGui.QLineEdit(self.pyFAI)
        self.pf_rotation1_txt.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.pf_rotation1_txt.setObjectName("pf_rotation1_txt")
        self.gridLayout_3.addWidget(self.pf_rotation1_txt, 5, 1, 1, 1)
        self.label_31 = QtGui.QLabel(self.pyFAI)
        self.label_31.setObjectName("label_31")
        self.gridLayout_3.addWidget(self.label_31, 5, 2, 1, 1)
        self.pf_rotation2_txt = QtGui.QLineEdit(self.pyFAI)
        self.pf_rotation2_txt.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.pf_rotation2_txt.setObjectName("pf_rotation2_txt")
        self.gridLayout_3.addWidget(self.pf_rotation2_txt, 6, 1, 1, 1)
        self.label_32 = QtGui.QLabel(self.pyFAI)
        self.label_32.setObjectName("label_32")
        self.gridLayout_3.addWidget(self.label_32, 6, 2, 1, 1)
        self.pf_rotation3_txt = QtGui.QLineEdit(self.pyFAI)
        self.pf_rotation3_txt.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.pf_rotation3_txt.setObjectName("pf_rotation3_txt")
        self.gridLayout_3.addWidget(self.pf_rotation3_txt, 7, 1, 1, 1)
        self.label_33 = QtGui.QLabel(self.pyFAI)
        self.label_33.setObjectName("label_33")
        self.gridLayout_3.addWidget(self.label_33, 7, 2, 1, 1)
        self.label_46 = QtGui.QLabel(self.pyFAI)
        self.label_46.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_46.setObjectName("label_46")
        self.gridLayout_3.addWidget(self.label_46, 8, 0, 1, 1)
        self.pf_pixel_width_txt = QtGui.QLineEdit(self.pyFAI)
        self.pf_pixel_width_txt.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.pf_pixel_width_txt.setObjectName("pf_pixel_width_txt")
        self.gridLayout_3.addWidget(self.pf_pixel_width_txt, 8, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.pyFAI)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 8, 2, 1, 1)
        self.label_47 = QtGui.QLabel(self.pyFAI)
        self.label_47.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_47.setObjectName("label_47")
        self.gridLayout_3.addWidget(self.label_47, 9, 0, 1, 1)
        self.pf_pixel_height_txt = QtGui.QLineEdit(self.pyFAI)
        self.pf_pixel_height_txt.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.pf_pixel_height_txt.setObjectName("pf_pixel_height_txt")
        self.gridLayout_3.addWidget(self.pf_pixel_height_txt, 9, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.pyFAI)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 9, 2, 1, 1)
        self.pf_update_btn = QtGui.QPushButton(self.pyFAI)
        self.pf_update_btn.setFlat(True)
        self.pf_update_btn.setObjectName("pf_update_btn")
        self.gridLayout_3.addWidget(self.pf_update_btn, 10, 0, 1, 4)
        spacerItem5 = QtGui.QSpacerItem(20, 94, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem5, 11, 1, 1, 1)
        self.pf_polarization_txt = QtGui.QLineEdit(self.pyFAI)
        self.pf_polarization_txt.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.pf_polarization_txt.setObjectName("pf_polarization_txt")
        self.gridLayout_3.addWidget(self.pf_polarization_txt, 2, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.pyFAI)
        self.label_15.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 2, 0, 1, 1)
        self.ToolBox.addItem(self.pyFAI, "")
        self.fit2d = QtGui.QWidget()
        self.fit2d.setGeometry(QtCore.QRect(0, 0, 430, 482))
        self.fit2d.setObjectName("fit2d")
        self.gridLayout_7 = QtGui.QGridLayout(self.fit2d)
        self.gridLayout_7.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_7.setHorizontalSpacing(8)
        self.gridLayout_7.setVerticalSpacing(12)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_35 = QtGui.QLabel(self.fit2d)
        self.label_35.setObjectName("label_35")
        self.gridLayout_7.addWidget(self.label_35, 3, 3, 1, 1)
        self.f2_pixel_width_txt = QtGui.QLineEdit(self.fit2d)
        self.f2_pixel_width_txt.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.f2_pixel_width_txt.setObjectName("f2_pixel_width_txt")
        self.gridLayout_7.addWidget(self.f2_pixel_width_txt, 7, 1, 1, 1)
        self.label_76 = QtGui.QLabel(self.fit2d)
        self.label_76.setObjectName("label_76")
        self.gridLayout_7.addWidget(self.label_76, 8, 3, 1, 1)
        self.label_77 = QtGui.QLabel(self.fit2d)
        self.label_77.setObjectName("label_77")
        self.gridLayout_7.addWidget(self.label_77, 7, 3, 1, 1)
        self.label_75 = QtGui.QLabel(self.fit2d)
        self.label_75.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_75.setObjectName("label_75")
        self.gridLayout_7.addWidget(self.label_75, 8, 0, 1, 1)
        self.f2_pixel_height_txt = QtGui.QLineEdit(self.fit2d)
        self.f2_pixel_height_txt.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.f2_pixel_height_txt.setObjectName("f2_pixel_height_txt")
        self.gridLayout_7.addWidget(self.f2_pixel_height_txt, 8, 1, 1, 1)
        self.label_34 = QtGui.QLabel(self.fit2d)
        self.label_34.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName("label_34")
        self.gridLayout_7.addWidget(self.label_34, 1, 0, 1, 1)
        self.label_36 = QtGui.QLabel(self.fit2d)
        self.label_36.setObjectName("label_36")
        self.gridLayout_7.addWidget(self.label_36, 0, 3, 1, 1)
        self.f2_distance_txt = QtGui.QLineEdit(self.fit2d)
        self.f2_distance_txt.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.f2_distance_txt.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.f2_distance_txt.setObjectName("f2_distance_txt")
        self.gridLayout_7.addWidget(self.f2_distance_txt, 0, 1, 1, 1)
        self.label_37 = QtGui.QLabel(self.fit2d)
        self.label_37.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName("label_37")
        self.gridLayout_7.addWidget(self.label_37, 0, 0, 1, 1)
        self.f2_update_btn = QtGui.QPushButton(self.fit2d)
        self.f2_update_btn.setFlat(True)
        self.f2_update_btn.setObjectName("f2_update_btn")
        self.gridLayout_7.addWidget(self.f2_update_btn, 9, 0, 1, 5)
        spacerItem6 = QtGui.QSpacerItem(20, 147, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem6, 10, 0, 1, 1)
        self.f2_wavelength_cb = QtGui.QCheckBox(self.fit2d)
        self.f2_wavelength_cb.setText("")
        self.f2_wavelength_cb.setObjectName("f2_wavelength_cb")
        self.gridLayout_7.addWidget(self.f2_wavelength_cb, 1, 4, 1, 1)
        self.label_39 = QtGui.QLabel(self.fit2d)
        self.label_39.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_39.setObjectName("label_39")
        self.gridLayout_7.addWidget(self.label_39, 3, 0, 1, 1)
        self.f2_center_x_txt = QtGui.QLineEdit(self.fit2d)
        self.f2_center_x_txt.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.f2_center_x_txt.setObjectName("f2_center_x_txt")
        self.gridLayout_7.addWidget(self.f2_center_x_txt, 3, 1, 1, 1)
        self.label_41 = QtGui.QLabel(self.fit2d)
        self.label_41.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_41.setObjectName("label_41")
        self.gridLayout_7.addWidget(self.label_41, 4, 0, 1, 1)
        self.f2_center_y_txt = QtGui.QLineEdit(self.fit2d)
        self.f2_center_y_txt.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.f2_center_y_txt.setObjectName("f2_center_y_txt")
        self.gridLayout_7.addWidget(self.f2_center_y_txt, 4, 1, 1, 1)
        self.label_40 = QtGui.QLabel(self.fit2d)
        self.label_40.setObjectName("label_40")
        self.gridLayout_7.addWidget(self.label_40, 4, 3, 1, 1)
        self.label_45 = QtGui.QLabel(self.fit2d)
        self.label_45.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_45.setObjectName("label_45")
        self.gridLayout_7.addWidget(self.label_45, 5, 0, 1, 1)
        self.f2_rotation_txt = QtGui.QLineEdit(self.fit2d)
        self.f2_rotation_txt.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.f2_rotation_txt.setObjectName("f2_rotation_txt")
        self.gridLayout_7.addWidget(self.f2_rotation_txt, 5, 1, 1, 1)
        self.f2_wavelength_txt = QtGui.QLineEdit(self.fit2d)
        self.f2_wavelength_txt.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.f2_wavelength_txt.setObjectName("f2_wavelength_txt")
        self.gridLayout_7.addWidget(self.f2_wavelength_txt, 1, 1, 1, 1)
        self.label_38 = QtGui.QLabel(self.fit2d)
        self.label_38.setObjectName("label_38")
        self.gridLayout_7.addWidget(self.label_38, 1, 3, 1, 1)
        self.label_44 = QtGui.QLabel(self.fit2d)
        self.label_44.setObjectName("label_44")
        self.gridLayout_7.addWidget(self.label_44, 5, 3, 1, 1)
        self.label_42 = QtGui.QLabel(self.fit2d)
        self.label_42.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_42.setObjectName("label_42")
        self.gridLayout_7.addWidget(self.label_42, 6, 0, 1, 1)
        self.f2_tilt_txt = QtGui.QLineEdit(self.fit2d)
        self.f2_tilt_txt.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.f2_tilt_txt.setObjectName("f2_tilt_txt")
        self.gridLayout_7.addWidget(self.f2_tilt_txt, 6, 1, 1, 1)
        self.label_43 = QtGui.QLabel(self.fit2d)
        self.label_43.setObjectName("label_43")
        self.gridLayout_7.addWidget(self.label_43, 6, 3, 1, 1)
        self.label_78 = QtGui.QLabel(self.fit2d)
        self.label_78.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_78.setObjectName("label_78")
        self.gridLayout_7.addWidget(self.label_78, 7, 0, 1, 1)
        self.f2_polarization_txt = QtGui.QLineEdit(self.fit2d)
        self.f2_polarization_txt.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.f2_polarization_txt.setObjectName("f2_polarization_txt")
        self.gridLayout_7.addWidget(self.f2_polarization_txt, 2, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.fit2d)
        self.label_16.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_7.addWidget(self.label_16, 2, 0, 1, 1)
        self.ToolBox.addItem(self.fit2d, "")
        self.verticalLayout_3.addWidget(self.ToolBox)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.load_calibration_btn = QtGui.QPushButton(self.widget)
        self.load_calibration_btn.setFlat(True)
        self.load_calibration_btn.setObjectName("load_calibration_btn")
        self.horizontalLayout.addWidget(self.load_calibration_btn)
        self.save_calibration_btn = QtGui.QPushButton(self.widget)
        self.save_calibration_btn.setFlat(True)
        self.save_calibration_btn.setObjectName("save_calibration_btn")
        self.horizontalLayout.addWidget(self.save_calibration_btn)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_6.addWidget(self.splitter)

        self.retranslateUi(XrsCalibrationWidget)
        self.tab_widget.setCurrentIndex(0)
        QtCore.QObject.connect(self.f2_wavelength_cb, QtCore.SIGNAL("clicked()"), self.pf_wavelength_cb.toggle)
        QtCore.QObject.connect(self.pf_wavelength_cb, QtCore.SIGNAL("clicked()"), self.f2_wavelength_cb.toggle)
        QtCore.QMetaObject.connectSlotsByName(XrsCalibrationWidget)
        XrsCalibrationWidget.setTabOrder(self.sv_distance_txt, self.sv_wavelength_txt)
        XrsCalibrationWidget.setTabOrder(self.sv_wavelength_txt, self.sv_polarization_txt)
        XrsCalibrationWidget.setTabOrder(self.sv_polarization_txt, self.sv_pixel_width_txt)
        XrsCalibrationWidget.setTabOrder(self.sv_pixel_width_txt, self.sv_pixel_height_txt)
        XrsCalibrationWidget.setTabOrder(self.sv_pixel_height_txt, self.calibrant_cb)
        XrsCalibrationWidget.setTabOrder(self.calibrant_cb, self.rotate_p90_btn)
        XrsCalibrationWidget.setTabOrder(self.rotate_p90_btn, self.rotate_m90_btn)
        XrsCalibrationWidget.setTabOrder(self.rotate_m90_btn, self.invert_horizontal_btn)
        XrsCalibrationWidget.setTabOrder(self.invert_horizontal_btn, self.invert_vertical_btn)
        XrsCalibrationWidget.setTabOrder(self.invert_vertical_btn, self.reset_transformations_btn)
        XrsCalibrationWidget.setTabOrder(self.reset_transformations_btn, self.peak_num_sb)
        XrsCalibrationWidget.setTabOrder(self.peak_num_sb, self.automatic_peak_num_inc_cb)
        XrsCalibrationWidget.setTabOrder(self.automatic_peak_num_inc_cb, self.automatic_peak_search_rb)
        XrsCalibrationWidget.setTabOrder(self.automatic_peak_search_rb, self.select_peak_rb)
        XrsCalibrationWidget.setTabOrder(self.select_peak_rb, self.search_size_sb)
        XrsCalibrationWidget.setTabOrder(self.search_size_sb, self.clear_peaks_btn)
        XrsCalibrationWidget.setTabOrder(self.clear_peaks_btn, self.options_peaksearch_algorithm_cb)
        XrsCalibrationWidget.setTabOrder(self.options_peaksearch_algorithm_cb, self.options_delta_tth_txt)
        XrsCalibrationWidget.setTabOrder(self.options_delta_tth_txt, self.options_intensity_mean_factor_sb)
        XrsCalibrationWidget.setTabOrder(self.options_intensity_mean_factor_sb, self.options_intensity_limit_txt)
        XrsCalibrationWidget.setTabOrder(self.options_intensity_limit_txt, self.options_num_rings_sb)
        XrsCalibrationWidget.setTabOrder(self.options_num_rings_sb, self.pf_distance_txt)
        XrsCalibrationWidget.setTabOrder(self.pf_distance_txt, self.pf_wavelength_txt)
        XrsCalibrationWidget.setTabOrder(self.pf_wavelength_txt, self.pf_polarization_txt)
        XrsCalibrationWidget.setTabOrder(self.pf_polarization_txt, self.pf_poni1_txt)
        XrsCalibrationWidget.setTabOrder(self.pf_poni1_txt, self.pf_poni2_txt)
        XrsCalibrationWidget.setTabOrder(self.pf_poni2_txt, self.pf_rotation1_txt)
        XrsCalibrationWidget.setTabOrder(self.pf_rotation1_txt, self.pf_rotation2_txt)
        XrsCalibrationWidget.setTabOrder(self.pf_rotation2_txt, self.pf_rotation3_txt)
        XrsCalibrationWidget.setTabOrder(self.pf_rotation3_txt, self.pf_pixel_width_txt)
        XrsCalibrationWidget.setTabOrder(self.pf_pixel_width_txt, self.pf_pixel_height_txt)
        XrsCalibrationWidget.setTabOrder(self.pf_pixel_height_txt, self.pf_wavelength_cb)
        XrsCalibrationWidget.setTabOrder(self.pf_wavelength_cb, self.pf_update_btn)
        XrsCalibrationWidget.setTabOrder(self.pf_update_btn, self.f2_distance_txt)
        XrsCalibrationWidget.setTabOrder(self.f2_distance_txt, self.f2_wavelength_txt)
        XrsCalibrationWidget.setTabOrder(self.f2_wavelength_txt, self.f2_polarization_txt)
        XrsCalibrationWidget.setTabOrder(self.f2_polarization_txt, self.f2_center_x_txt)
        XrsCalibrationWidget.setTabOrder(self.f2_center_x_txt, self.f2_center_y_txt)
        XrsCalibrationWidget.setTabOrder(self.f2_center_y_txt, self.f2_rotation_txt)
        XrsCalibrationWidget.setTabOrder(self.f2_rotation_txt, self.f2_tilt_txt)
        XrsCalibrationWidget.setTabOrder(self.f2_tilt_txt, self.f2_pixel_width_txt)
        XrsCalibrationWidget.setTabOrder(self.f2_pixel_width_txt, self.f2_pixel_height_txt)
        XrsCalibrationWidget.setTabOrder(self.f2_pixel_height_txt, self.f2_wavelength_cb)
        XrsCalibrationWidget.setTabOrder(self.f2_wavelength_cb, self.f2_update_btn)
        XrsCalibrationWidget.setTabOrder(self.f2_update_btn, self.load_img_btn)
        XrsCalibrationWidget.setTabOrder(self.load_img_btn, self.load_calibration_btn)
        XrsCalibrationWidget.setTabOrder(self.load_calibration_btn, self.save_calibration_btn)
        XrsCalibrationWidget.setTabOrder(self.save_calibration_btn, self.refine_btn)
        XrsCalibrationWidget.setTabOrder(self.refine_btn, self.tab_widget)
        XrsCalibrationWidget.setTabOrder(self.tab_widget, self.img_pg_layout)
        XrsCalibrationWidget.setTabOrder(self.img_pg_layout, self.cake_pg_layout)
        XrsCalibrationWidget.setTabOrder(self.cake_pg_layout, self.integrate_btn)
        XrsCalibrationWidget.setTabOrder(self.integrate_btn, self.spectrum_pg_layout)

    def retranslateUi(self, XrsCalibrationWidget):
        XrsCalibrationWidget.setWindowTitle(
            QtGui.QApplication.translate("XrsCalibrationWidget", "XRS Calibration", None,
                                         QtGui.QApplication.UnicodeUTF8))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab),
                                   QtGui.QApplication.translate("XrsCalibrationWidget", "Image", None,
                                                                QtGui.QApplication.UnicodeUTF8))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_2),
                                   QtGui.QApplication.translate("XrsCalibrationWidget", "Cake", None,
                                                                QtGui.QApplication.UnicodeUTF8))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_3),
                                   QtGui.QApplication.translate("XrsCalibrationWidget", "Spectrum", None,
                                                                QtGui.QApplication.UnicodeUTF8))
        self.integrate_btn.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "Calibrate", None, QtGui.QApplication.UnicodeUTF8))
        self.refine_btn.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "Refine", None, QtGui.QApplication.UnicodeUTF8))
        self.pos_lbl.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "Position", None, QtGui.QApplication.UnicodeUTF8))
        self.load_img_btn.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "Load Image", None, QtGui.QApplication.UnicodeUTF8))
        self.load_previous_img_btn.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.load_next_img_btn.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.filename_lbl.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "Filename", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(
            QtGui.QApplication.translate("XrsCalibrationWidget", "Start Values", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "Pixelwidth:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "μm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "Pixelheight:", None, QtGui.QApplication.UnicodeUTF8))
        self.sv_pixel_height_txt.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "200", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "μm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "Calibrant:", None, QtGui.QApplication.UnicodeUTF8))
        self.sv_pixel_width_txt.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "200", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "Distance:", None, QtGui.QApplication.UnicodeUTF8))
        self.sv_distance_txt.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "400", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "Wavelength:", None, QtGui.QApplication.UnicodeUTF8))
        self.sv_wavelength_txt.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "0.4133", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "Å", None, QtGui.QApplication.UnicodeUTF8))
        self.sv_polarization_txt.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "0.95", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "Polarization:", None, QtGui.QApplication.UnicodeUTF8))
        self.rotate_p90_btn.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "Rotate +90°", None, QtGui.QApplication.UnicodeUTF8))
        self.rotate_m90_btn.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "Rotate -90°", None, QtGui.QApplication.UnicodeUTF8))
        self.invert_horizontal_btn.setText(QtGui.QApplication.translate("XrsCalibrationWidget", "Flip horizontal", None,
                                                                        QtGui.QApplication.UnicodeUTF8))
        self.invert_vertical_btn.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "Flip vertical", None, QtGui.QApplication.UnicodeUTF8))
        self.reset_transformations_btn.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "Reset Transformations", None,
                                         QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("XrsCalibrationWidget", "Peak Selection", None,
                                                              QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("XrsCalibrationWidget", "Current peaknumber:", None,
                                                           QtGui.QApplication.UnicodeUTF8))
        self.automatic_peak_num_inc_cb.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "automatic increase", None,
                                         QtGui.QApplication.UnicodeUTF8))
        self.automatic_peak_search_rb.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "automatic peak  search (APS)", None,
                                         QtGui.QApplication.UnicodeUTF8))
        self.select_peak_rb.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "single peak search (SPS)", None,
                                         QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("XrsCalibrationWidget", "SPS searchsize:", None,
                                                           QtGui.QApplication.UnicodeUTF8))
        self.clear_peaks_btn.setText(QtGui.QApplication.translate("XrsCalibrationWidget", "Clear All Peaks", None,
                                                                  QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("XrsCalibrationWidget", "Refinement Options", None,
                                                            QtGui.QApplication.UnicodeUTF8))
        self.options_intensity_limit_txt.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "55000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("XrsCalibrationWidget", "Peaksearch algorithm:", None,
                                                           QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("XrsCalibrationWidget", "Number of Rings:", None,
                                                           QtGui.QApplication.UnicodeUTF8))
        self.options_delta_tth_txt.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("XrsCalibrationWidget", "Intensity Max:", None,
                                                           QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("XrsCalibrationWidget", "Intensity Min factor:", None,
                                                           QtGui.QApplication.UnicodeUTF8))
        self.options_peaksearch_algorithm_cb.setItemText(0,
                                                         QtGui.QApplication.translate("XrsCalibrationWidget", "Massif",
                                                                                      None,
                                                                                      QtGui.QApplication.UnicodeUTF8))
        self.options_peaksearch_algorithm_cb.setItemText(1, QtGui.QApplication.translate("XrsCalibrationWidget", "Blob",
                                                                                         None,
                                                                                         QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "Delta 2Th:", None, QtGui.QApplication.UnicodeUTF8))
        self.options_automatic_refinement_cb.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "automatic refinement", None,
                                         QtGui.QApplication.UnicodeUTF8))
        self.ToolBox.setItemText(self.ToolBox.indexOf(self.start_values),
                                 QtGui.QApplication.translate("XrsCalibrationWidget", "Calibration Parameters", None,
                                                              QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "Å", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "Wavelength:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "Distance:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "PONI:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "Rotations:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "rad", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "rad", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "rad", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "Pixelwidth:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "μm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_47.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "Pixelheight:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "μm", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_update_btn.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "Polarization:", None, QtGui.QApplication.UnicodeUTF8))
        self.ToolBox.setItemText(self.ToolBox.indexOf(self.pyFAI),
                                 QtGui.QApplication.translate("XrsCalibrationWidget", "pyFAI Parameters", None,
                                                              QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "px", None, QtGui.QApplication.UnicodeUTF8))
        self.label_76.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "μm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_77.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "μm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_75.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "Pixelheight:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "Wavelength:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "Distance:", None, QtGui.QApplication.UnicodeUTF8))
        self.f2_update_btn.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "Center X:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "Center Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "px", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "Rotation:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "Å", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "deg", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "Tilt:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "deg", None, QtGui.QApplication.UnicodeUTF8))
        self.label_78.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "Pixelwidth:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(
            QtGui.QApplication.translate("XrsCalibrationWidget", "Polarization:", None, QtGui.QApplication.UnicodeUTF8))
        self.ToolBox.setItemText(self.ToolBox.indexOf(self.fit2d),
                                 QtGui.QApplication.translate("XrsCalibrationWidget", "Fit2D Parameters", None,
                                                              QtGui.QApplication.UnicodeUTF8))
        self.load_calibration_btn.setText(QtGui.QApplication.translate("XrsCalibrationWidget", "Load Calibration", None,
                                                                       QtGui.QApplication.UnicodeUTF8))
        self.save_calibration_btn.setText(QtGui.QApplication.translate("XrsCalibrationWidget", "Save Calibration", None,
                                                                       QtGui.QApplication.UnicodeUTF8))


from pyqtgraph import GraphicsLayoutWidget
