# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Integration.ui'
#
# Created: Mon Jun  9 19:38:59 2014
# by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui


class Ui_xrs_integration_widget(object):
    def setupUi(self, xrs_integration_widget):
        xrs_integration_widget.setObjectName("xrs_integration_widget")
        xrs_integration_widget.resize(1307, 823)
        xrs_integration_widget.setStyleSheet("\n"
                                             "\n"
                                             "#image_frame, #spec_container_widget, #spec_btn_widget {\n"
                                             "    background: black;\n"
                                             "}\n"
                                             "#spec_btn_widget QPushButton{\n"
                                             "    padding: 0px;\n"
                                             "    padding-right: 1px;\n"
                                             "    border-radius: 3px;\n"
                                             "}\n"
                                             "\n"
                                             "#image_frame QPushButton{\n"
                                             "    padding-left: 4px;\n"
                                             "    padding-right: 4px;\n"
                                             "}\n"
                                             "\n"
                                             "#spec_btn_widget QPushButton::pressed, #image_frame QPushButton::pressed{\n"
                                             "    margin: 0px;\n"
                                             "}\n"
                                             "\n"
                                             "")
        self.verticalLayout_16 = QtGui.QVBoxLayout(xrs_integration_widget)
        self.verticalLayout_16.setSpacing(3)
        self.verticalLayout_16.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontal_splitter = QtGui.QSplitter(xrs_integration_widget)
        self.horizontal_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.horizontal_splitter.setObjectName("horizontal_splitter")
        self.image_frame = QtGui.QFrame(self.horizontal_splitter)
        self.image_frame.setStyleSheet("")
        self.image_frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.image_frame.setObjectName("image_frame")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.image_frame)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.img_pg_layout = GraphicsLayoutWidget(self.image_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_pg_layout.sizePolicy().hasHeightForWidth())
        self.img_pg_layout.setSizePolicy(sizePolicy)
        self.img_pg_layout.setMinimumSize(QtCore.QSize(200, 0))
        self.img_pg_layout.setBaseSize(QtCore.QSize(300, 0))
        self.img_pg_layout.setFrameShape(QtGui.QFrame.StyledPanel)
        self.img_pg_layout.setObjectName("img_pg_layout")
        self.verticalLayout_9.addWidget(self.img_pg_layout)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setSpacing(8)
        self.horizontalLayout_30.setContentsMargins(8, -1, 8, 8)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.img_mode_btn = QtGui.QPushButton(self.image_frame)
        self.img_mode_btn.setMinimumSize(QtCore.QSize(50, 0))
        self.img_mode_btn.setFlat(True)
        self.img_mode_btn.setObjectName("img_mode_btn")
        self.horizontalLayout_30.addWidget(self.img_mode_btn)
        self.img_mask_btn = QtGui.QPushButton(self.image_frame)
        self.img_mask_btn.setCheckable(True)
        self.img_mask_btn.setFlat(True)
        self.img_mask_btn.setObjectName("img_mask_btn")
        self.horizontalLayout_30.addWidget(self.img_mask_btn)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.horizontalLayout_30.addLayout(self.horizontalLayout_25)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem)
        self.img_autoscale_btn = QtGui.QPushButton(self.image_frame)
        self.img_autoscale_btn.setFlat(True)
        self.img_autoscale_btn.setObjectName("img_autoscale_btn")
        self.horizontalLayout_30.addWidget(self.img_autoscale_btn)
        self.verticalLayout_9.addLayout(self.horizontalLayout_30)
        self.vertical_splitter = QtGui.QSplitter(self.horizontal_splitter)
        self.vertical_splitter.setOrientation(QtCore.Qt.Vertical)
        self.vertical_splitter.setObjectName("vertical_splitter")
        self.tabWidget = QtGui.QTabWidget(self.vertical_splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.image_tab = QtGui.QWidget()
        self.image_tab.setObjectName("image_tab")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.image_tab)
        self.verticalLayout_11.setSpacing(8)
        self.verticalLayout_11.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.frame = QtGui.QFrame(self.image_tab)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.load_img_btn = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_img_btn.sizePolicy().hasHeightForWidth())
        self.load_img_btn.setSizePolicy(sizePolicy)
        self.load_img_btn.setMinimumSize(QtCore.QSize(75, 0))
        self.load_img_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.load_img_btn.setFlat(True)
        self.load_img_btn.setObjectName("load_img_btn")
        self.horizontalLayout_2.addWidget(self.load_img_btn)
        self.prev_img_btn = QtGui.QPushButton(self.frame)
        self.prev_img_btn.setMinimumSize(QtCore.QSize(50, 0))
        self.prev_img_btn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.prev_img_btn.setFlat(True)
        self.prev_img_btn.setObjectName("prev_img_btn")
        self.horizontalLayout_2.addWidget(self.prev_img_btn)
        self.next_img_btn = QtGui.QPushButton(self.frame)
        self.next_img_btn.setMinimumSize(QtCore.QSize(50, 0))
        self.next_img_btn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.next_img_btn.setFlat(True)
        self.next_img_btn.setObjectName("next_img_btn")
        self.horizontalLayout_2.addWidget(self.next_img_btn)
        self.auto_img_btn = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.auto_img_btn.sizePolicy().hasHeightForWidth())
        self.auto_img_btn.setSizePolicy(sizePolicy)
        self.auto_img_btn.setFlat(True)
        self.auto_img_btn.setObjectName("auto_img_btn")
        self.horizontalLayout_2.addWidget(self.auto_img_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.img_browse_by_name_rb = QtGui.QRadioButton(self.frame)
        self.img_browse_by_name_rb.setChecked(True)
        self.img_browse_by_name_rb.setObjectName("img_browse_by_name_rb")
        self.horizontalLayout_17.addWidget(self.img_browse_by_name_rb)
        self.img_browse_by_time_rb = QtGui.QRadioButton(self.frame)
        self.img_browse_by_time_rb.setObjectName("img_browse_by_time_rb")
        self.horizontalLayout_17.addWidget(self.img_browse_by_time_rb)
        self.autoprocess_cb = QtGui.QCheckBox(self.frame)
        self.autoprocess_cb.setAutoExclusive(False)
        self.autoprocess_cb.setTristate(False)
        self.autoprocess_cb.setObjectName("autoprocess_cb")
        self.horizontalLayout_17.addWidget(self.autoprocess_cb)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18.addWidget(self.frame)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.img_filename_lbl = QtGui.QLabel(self.image_tab)
        self.img_filename_lbl.setObjectName("img_filename_lbl")
        self.verticalLayout_10.addWidget(self.img_filename_lbl)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setSpacing(5)
        self.horizontalLayout_26.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.spec_directory_txt_2 = QtGui.QLineEdit(self.image_tab)
        self.spec_directory_txt_2.setMinimumSize(QtCore.QSize(0, 0))
        self.spec_directory_txt_2.setObjectName("spec_directory_txt_2")
        self.horizontalLayout_26.addWidget(self.spec_directory_txt_2)
        self.spec_directory_btn_2 = QtGui.QPushButton(self.image_tab)
        self.spec_directory_btn_2.setFlat(True)
        self.spec_directory_btn_2.setObjectName("spec_directory_btn_2")
        self.horizontalLayout_26.addWidget(self.spec_directory_btn_2)
        self.verticalLayout_10.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_18.addLayout(self.verticalLayout_10)
        self.verticalLayout_11.addLayout(self.horizontalLayout_18)
        spacerItem1 = QtGui.QSpacerItem(20, 55, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem1)
        self.widget_2 = QtGui.QWidget(self.image_tab)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_23 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_23.setSpacing(-1)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.qa_image_save_img_btn = QtGui.QPushButton(self.widget_2)
        self.qa_image_save_img_btn.setFlat(True)
        self.qa_image_save_img_btn.setObjectName("qa_image_save_img_btn")
        self.horizontalLayout_23.addWidget(self.qa_image_save_img_btn)
        self.qa_image_save_spectrum_btn = QtGui.QPushButton(self.widget_2)
        self.qa_image_save_spectrum_btn.setFlat(True)
        self.qa_image_save_spectrum_btn.setObjectName("qa_image_save_spectrum_btn")
        self.horizontalLayout_23.addWidget(self.qa_image_save_spectrum_btn)
        self.qa_image_set_as_overlay_btn = QtGui.QPushButton(self.widget_2)
        self.qa_image_set_as_overlay_btn.setFlat(True)
        self.qa_image_set_as_overlay_btn.setObjectName("qa_image_set_as_overlay_btn")
        self.horizontalLayout_23.addWidget(self.qa_image_set_as_overlay_btn)
        self.qa_image_set_as_background_btn = QtGui.QPushButton(self.widget_2)
        self.qa_image_set_as_background_btn.setFlat(True)
        self.qa_image_set_as_background_btn.setObjectName("qa_image_set_as_background_btn")
        self.horizontalLayout_23.addWidget(self.qa_image_set_as_background_btn)
        spacerItem2 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem2)
        self.image_load_calibration_btn = QtGui.QPushButton(self.widget_2)
        self.image_load_calibration_btn.setFlat(True)
        self.image_load_calibration_btn.setObjectName("image_load_calibration_btn")
        self.horizontalLayout_23.addWidget(self.image_load_calibration_btn)
        self.calibration_lbl = QtGui.QLabel(self.widget_2)
        self.calibration_lbl.setObjectName("calibration_lbl")
        self.horizontalLayout_23.addWidget(self.calibration_lbl)
        self.verticalLayout_11.addWidget(self.widget_2)
        self.tabWidget.addTab(self.image_tab, "")
        self.spectra_tab = QtGui.QWidget()
        self.spectra_tab.setObjectName("spectra_tab")
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.spectra_tab)
        self.verticalLayout_13.setSpacing(8)
        self.verticalLayout_13.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_2 = QtGui.QFrame(self.spectra_tab)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(8)
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.spec_load_btn = QtGui.QPushButton(self.frame_2)
        self.spec_load_btn.setMinimumSize(QtCore.QSize(75, 0))
        self.spec_load_btn.setMaximumSize(QtCore.QSize(75, 16777215))
        self.spec_load_btn.setFlat(True)
        self.spec_load_btn.setObjectName("spec_load_btn")
        self.horizontalLayout_4.addWidget(self.spec_load_btn)
        self.spec_previous_btn = QtGui.QPushButton(self.frame_2)
        self.spec_previous_btn.setMinimumSize(QtCore.QSize(10, 0))
        self.spec_previous_btn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spec_previous_btn.setFlat(True)
        self.spec_previous_btn.setObjectName("spec_previous_btn")
        self.horizontalLayout_4.addWidget(self.spec_previous_btn)
        self.spec_next_btn = QtGui.QPushButton(self.frame_2)
        self.spec_next_btn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spec_next_btn.setFlat(True)
        self.spec_next_btn.setObjectName("spec_next_btn")
        self.horizontalLayout_4.addWidget(self.spec_next_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.spec_browse_by_name_rb = QtGui.QRadioButton(self.frame_2)
        self.spec_browse_by_name_rb.setChecked(True)
        self.spec_browse_by_name_rb.setObjectName("spec_browse_by_name_rb")
        self.horizontalLayout.addWidget(self.spec_browse_by_name_rb)
        self.spec_browse_by_time_rb = QtGui.QRadioButton(self.frame_2)
        self.spec_browse_by_time_rb.setObjectName("spec_browse_by_time_rb")
        self.horizontalLayout.addWidget(self.spec_browse_by_time_rb)
        self.spec_autocreate_cb = QtGui.QCheckBox(self.frame_2)
        self.spec_autocreate_cb.setChecked(False)
        self.spec_autocreate_cb.setObjectName("spec_autocreate_cb")
        self.horizontalLayout.addWidget(self.spec_autocreate_cb)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_11.addWidget(self.frame_2)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.spec_filename_lbl = QtGui.QLabel(self.spectra_tab)
        self.spec_filename_lbl.setObjectName("spec_filename_lbl")
        self.verticalLayout_12.addWidget(self.spec_filename_lbl)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.spec_directory_txt = QtGui.QLineEdit(self.spectra_tab)
        self.spec_directory_txt.setObjectName("spec_directory_txt")
        self.horizontalLayout_10.addWidget(self.spec_directory_txt)
        self.spec_directory_btn = QtGui.QPushButton(self.spectra_tab)
        self.spec_directory_btn.setFlat(True)
        self.spec_directory_btn.setObjectName("spec_directory_btn")
        self.horizontalLayout_10.addWidget(self.spec_directory_btn)
        self.verticalLayout_12.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11.addLayout(self.verticalLayout_12)
        self.verticalLayout_13.addLayout(self.horizontalLayout_11)
        spacerItem3 = QtGui.QSpacerItem(20, 228, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem3)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.qa_spectrum_save_spectrum_btn = QtGui.QPushButton(self.spectra_tab)
        self.qa_spectrum_save_spectrum_btn.setFlat(True)
        self.qa_spectrum_save_spectrum_btn.setObjectName("qa_spectrum_save_spectrum_btn")
        self.horizontalLayout_22.addWidget(self.qa_spectrum_save_spectrum_btn)
        self.qa_spectrum_set_as_overlay_btn = QtGui.QPushButton(self.spectra_tab)
        self.qa_spectrum_set_as_overlay_btn.setAutoDefault(False)
        self.qa_spectrum_set_as_overlay_btn.setFlat(True)
        self.qa_spectrum_set_as_overlay_btn.setObjectName("qa_spectrum_set_as_overlay_btn")
        self.horizontalLayout_22.addWidget(self.qa_spectrum_set_as_overlay_btn)
        self.qa_spectrum_set_as_background_btn = QtGui.QPushButton(self.spectra_tab)
        self.qa_spectrum_set_as_background_btn.setFlat(True)
        self.qa_spectrum_set_as_background_btn.setObjectName("qa_spectrum_set_as_background_btn")
        self.horizontalLayout_22.addWidget(self.qa_spectrum_set_as_background_btn)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem4)
        self.verticalLayout_13.addLayout(self.horizontalLayout_22)
        self.tabWidget.addTab(self.spectra_tab, "")
        self.overlay_tab = QtGui.QWidget()
        self.overlay_tab.setObjectName("overlay_tab")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.overlay_tab)
        self.verticalLayout_6.setSpacing(5)
        self.verticalLayout_6.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.overlay_add_btn = QtGui.QPushButton(self.overlay_tab)
        self.overlay_add_btn.setFlat(True)
        self.overlay_add_btn.setObjectName("overlay_add_btn")
        self.horizontalLayout_3.addWidget(self.overlay_add_btn)
        self.overlay_del_btn = QtGui.QPushButton(self.overlay_tab)
        self.overlay_del_btn.setFlat(True)
        self.overlay_del_btn.setObjectName("overlay_del_btn")
        self.horizontalLayout_3.addWidget(self.overlay_del_btn)
        self.overlay_clear_btn = QtGui.QPushButton(self.overlay_tab)
        self.overlay_clear_btn.setFlat(True)
        self.overlay_clear_btn.setObjectName("overlay_clear_btn")
        self.horizontalLayout_3.addWidget(self.overlay_clear_btn)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.overlay_lw = QtGui.QListWidget(self.overlay_tab)
        self.overlay_lw.setObjectName("overlay_lw")
        self.horizontalLayout_6.addWidget(self.overlay_lw)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSpacing(8)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtGui.QLabel(self.overlay_tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.overlay_scale_sb = QtGui.QDoubleSpinBox(self.overlay_tab)
        self.overlay_scale_sb.setMinimumSize(QtCore.QSize(90, 0))
        self.overlay_scale_sb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.overlay_scale_sb.setDecimals(4)
        self.overlay_scale_sb.setMaximum(999999.0)
        self.overlay_scale_sb.setSingleStep(0.01)
        self.overlay_scale_sb.setObjectName("overlay_scale_sb")
        self.gridLayout.addWidget(self.overlay_scale_sb, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.overlay_tab)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.overlay_offset_sb = QtGui.QDoubleSpinBox(self.overlay_tab)
        self.overlay_offset_sb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.overlay_offset_sb.setDecimals(3)
        self.overlay_offset_sb.setMinimum(-999999999.0)
        self.overlay_offset_sb.setMaximum(999999999.0)
        self.overlay_offset_sb.setSingleStep(100.0)
        self.overlay_offset_sb.setProperty("value", 0.0)
        self.overlay_offset_sb.setObjectName("overlay_offset_sb")
        self.gridLayout.addWidget(self.overlay_offset_sb, 2, 1, 1, 1)
        self.overlay_show_cb = QtGui.QCheckBox(self.overlay_tab)
        self.overlay_show_cb.setChecked(True)
        self.overlay_show_cb.setObjectName("overlay_show_cb")
        self.gridLayout.addWidget(self.overlay_show_cb, 3, 0, 1, 3)
        self.overlay_scale_step_txt = QtGui.QLineEdit(self.overlay_tab)
        self.overlay_scale_step_txt.setMaximumSize(QtCore.QSize(80, 16777215))
        self.overlay_scale_step_txt.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.overlay_scale_step_txt.setObjectName("overlay_scale_step_txt")
        self.gridLayout.addWidget(self.overlay_scale_step_txt, 1, 2, 1, 1)
        self.overlay_offset_step_txt = QtGui.QLineEdit(self.overlay_tab)
        self.overlay_offset_step_txt.setMaximumSize(QtCore.QSize(80, 16777215))
        self.overlay_offset_step_txt.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.overlay_offset_step_txt.setObjectName("overlay_offset_step_txt")
        self.gridLayout.addWidget(self.overlay_offset_step_txt, 2, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.overlay_tab)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem5)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.overlay_save_set_btn = QtGui.QPushButton(self.overlay_tab)
        self.overlay_save_set_btn.setFlat(True)
        self.overlay_save_set_btn.setObjectName("overlay_save_set_btn")
        self.horizontalLayout_5.addWidget(self.overlay_save_set_btn)
        self.overlay_load_set_btn = QtGui.QPushButton(self.overlay_tab)
        self.overlay_load_set_btn.setFlat(True)
        self.overlay_load_set_btn.setObjectName("overlay_load_set_btn")
        self.horizontalLayout_5.addWidget(self.overlay_load_set_btn)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.overlay_set_as_bkg_btn = QtGui.QPushButton(self.overlay_tab)
        self.overlay_set_as_bkg_btn.setCheckable(True)
        self.overlay_set_as_bkg_btn.setObjectName("overlay_set_as_bkg_btn")
        self.horizontalLayout_5.addWidget(self.overlay_set_as_bkg_btn)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.tabWidget.addTab(self.overlay_tab, "")
        self.phase_tab = QtGui.QWidget()
        self.phase_tab.setObjectName("phase_tab")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.phase_tab)
        self.verticalLayout_8.setSpacing(5)
        self.verticalLayout_8.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(8)
        self.horizontalLayout_7.setContentsMargins(8, 0, 8, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.phase_add_btn = QtGui.QPushButton(self.phase_tab)
        self.phase_add_btn.setFlat(True)
        self.phase_add_btn.setObjectName("phase_add_btn")
        self.horizontalLayout_7.addWidget(self.phase_add_btn)
        self.phase_edit_btn = QtGui.QPushButton(self.phase_tab)
        self.phase_edit_btn.setFlat(True)
        self.phase_edit_btn.setObjectName("phase_edit_btn")
        self.horizontalLayout_7.addWidget(self.phase_edit_btn)
        self.phase_del_btn = QtGui.QPushButton(self.phase_tab)
        self.phase_del_btn.setFlat(True)
        self.phase_del_btn.setObjectName("phase_del_btn")
        self.horizontalLayout_7.addWidget(self.phase_del_btn)
        self.phase_clear_btn = QtGui.QPushButton(self.phase_tab)
        self.phase_clear_btn.setFlat(True)
        self.phase_clear_btn.setObjectName("phase_clear_btn")
        self.horizontalLayout_7.addWidget(self.phase_clear_btn)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.phase_lw = QtGui.QListWidget(self.phase_tab)
        self.phase_lw.setObjectName("phase_lw")
        self.horizontalLayout_9.addWidget(self.phase_lw)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_2.setSpacing(8)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtGui.QLabel(self.phase_tab)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 2, 1, 1)
        self.label = QtGui.QLabel(self.phase_tab)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.phase_pressure_sb = QtGui.QDoubleSpinBox(self.phase_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phase_pressure_sb.sizePolicy().hasHeightForWidth())
        self.phase_pressure_sb.setSizePolicy(sizePolicy)
        self.phase_pressure_sb.setMinimumSize(QtCore.QSize(110, 0))
        self.phase_pressure_sb.setSizeIncrement(QtCore.QSize(2, 0))
        self.phase_pressure_sb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.phase_pressure_sb.setMinimum(-999999999.0)
        self.phase_pressure_sb.setMaximum(999999999.0)
        self.phase_pressure_sb.setSingleStep(0.5)
        self.phase_pressure_sb.setObjectName("phase_pressure_sb")
        self.gridLayout_2.addWidget(self.phase_pressure_sb, 1, 1, 1, 1)
        self.phase_pressure_step_txt = QtGui.QLineEdit(self.phase_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phase_pressure_step_txt.sizePolicy().hasHeightForWidth())
        self.phase_pressure_step_txt.setSizePolicy(sizePolicy)
        self.phase_pressure_step_txt.setMaximumSize(QtCore.QSize(80, 16777215))
        self.phase_pressure_step_txt.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.phase_pressure_step_txt.setObjectName("phase_pressure_step_txt")
        self.gridLayout_2.addWidget(self.phase_pressure_step_txt, 1, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.phase_tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.phase_temperature_sb = QtGui.QDoubleSpinBox(self.phase_tab)
        self.phase_temperature_sb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.phase_temperature_sb.setMaximum(999999999.0)
        self.phase_temperature_sb.setSingleStep(100.0)
        self.phase_temperature_sb.setObjectName("phase_temperature_sb")
        self.gridLayout_2.addWidget(self.phase_temperature_sb, 2, 1, 1, 1)
        self.phase_temperature_step_txt = QtGui.QLineEdit(self.phase_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phase_temperature_step_txt.sizePolicy().hasHeightForWidth())
        self.phase_temperature_step_txt.setSizePolicy(sizePolicy)
        self.phase_temperature_step_txt.setMaximumSize(QtCore.QSize(80, 16777215))
        self.phase_temperature_step_txt.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.phase_temperature_step_txt.setObjectName("phase_temperature_step_txt")
        self.gridLayout_2.addWidget(self.phase_temperature_step_txt, 2, 2, 1, 1)
        self.phase_apply_to_all_cb = QtGui.QCheckBox(self.phase_tab)
        self.phase_apply_to_all_cb.setChecked(True)
        self.phase_apply_to_all_cb.setObjectName("phase_apply_to_all_cb")
        self.gridLayout_2.addWidget(self.phase_apply_to_all_cb, 3, 0, 1, 3)
        self.verticalLayout_7.addLayout(self.gridLayout_2)
        spacerItem7 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem7)
        self.horizontalLayout_9.addLayout(self.verticalLayout_7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(8)
        self.horizontalLayout_8.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.phase_save_set_btn = QtGui.QPushButton(self.phase_tab)
        self.phase_save_set_btn.setFlat(True)
        self.phase_save_set_btn.setObjectName("phase_save_set_btn")
        self.horizontalLayout_8.addWidget(self.phase_save_set_btn)
        self.phase_load_set_btn = QtGui.QPushButton(self.phase_tab)
        self.phase_load_set_btn.setFlat(True)
        self.phase_load_set_btn.setObjectName("phase_load_set_btn")
        self.horizontalLayout_8.addWidget(self.phase_load_set_btn)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.tabWidget.addTab(self.phase_tab, "")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.special_tab = QtGui.QWidget()
        self.special_tab.setObjectName("special_tab")
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.special_tab)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setSpacing(5)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.groupBox = QtGui.QGroupBox(self.special_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 43))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 50))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_14.setSpacing(14)
        self.horizontalLayout_14.setContentsMargins(8, 8, 13, 8)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.mask_transparent_cb = QtGui.QCheckBox(self.groupBox)
        self.mask_transparent_cb.setObjectName("mask_transparent_cb")
        self.horizontalLayout_14.addWidget(self.mask_transparent_cb)
        self.horizontalLayout_19.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.special_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 43))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_15.setSpacing(8)
        self.horizontalLayout_15.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.img_levels_autoscale_rb = QtGui.QRadioButton(self.groupBox_2)
        self.img_levels_autoscale_rb.setChecked(True)
        self.img_levels_autoscale_rb.setObjectName("img_levels_autoscale_rb")
        self.horizontalLayout_15.addWidget(self.img_levels_autoscale_rb)
        self.img_levels_absolute_rb = QtGui.QRadioButton(self.groupBox_2)
        self.img_levels_absolute_rb.setChecked(False)
        self.img_levels_absolute_rb.setObjectName("img_levels_absolute_rb")
        self.horizontalLayout_15.addWidget(self.img_levels_absolute_rb)
        self.img_levels_percentage_rb = QtGui.QRadioButton(self.groupBox_2)
        self.img_levels_percentage_rb.setObjectName("img_levels_percentage_rb")
        self.horizontalLayout_15.addWidget(self.img_levels_percentage_rb)
        self.horizontalLayout_19.addWidget(self.groupBox_2)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem9)
        self.verticalLayout_17.addLayout(self.horizontalLayout_19)
        spacerItem10 = QtGui.QSpacerItem(20, 433, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem10)
        self.tabWidget.addTab(self.special_tab, "")
        self.spec_container_widget = QtGui.QWidget(self.vertical_splitter)
        self.spec_container_widget.setObjectName("spec_container_widget")
        self.horizontalLayout_31 = QtGui.QHBoxLayout(self.spec_container_widget)
        self.horizontalLayout_31.setSpacing(0)
        self.horizontalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.spectrum_pg_layout = GraphicsLayoutWidget(self.spec_container_widget)
        self.spectrum_pg_layout.setSizeIncrement(QtCore.QSize(1, 2))
        self.spectrum_pg_layout.setBaseSize(QtCore.QSize(300, 300))
        self.spectrum_pg_layout.setFrameShape(QtGui.QFrame.StyledPanel)
        self.spectrum_pg_layout.setFrameShadow(QtGui.QFrame.Sunken)
        self.spectrum_pg_layout.setObjectName("spectrum_pg_layout")
        self.horizontalLayout_31.addWidget(self.spectrum_pg_layout)
        self.spec_btn_widget = QtGui.QWidget(self.spec_container_widget)
        self.spec_btn_widget.setObjectName("spec_btn_widget")
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.spec_btn_widget)
        self.verticalLayout_15.setSpacing(4)
        self.verticalLayout_15.setContentsMargins(0, 4, 4, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.spec_tth_btn = QtGui.QPushButton(self.spec_btn_widget)
        self.spec_tth_btn.setCheckable(True)
        self.spec_tth_btn.setChecked(True)
        self.spec_tth_btn.setFlat(True)
        self.spec_tth_btn.setObjectName("spec_tth_btn")
        self.verticalLayout_15.addWidget(self.spec_tth_btn)
        self.spec_q_btn = QtGui.QPushButton(self.spec_btn_widget)
        self.spec_q_btn.setCheckable(True)
        self.spec_q_btn.setFlat(True)
        self.spec_q_btn.setObjectName("spec_q_btn")
        self.verticalLayout_15.addWidget(self.spec_q_btn)
        self.spec_d_btn = QtGui.QPushButton(self.spec_btn_widget)
        self.spec_d_btn.setCheckable(True)
        self.spec_d_btn.setFlat(True)
        self.spec_d_btn.setObjectName("spec_d_btn")
        self.verticalLayout_15.addWidget(self.spec_d_btn)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem11)
        self.horizontalLayout_31.addWidget(self.spec_btn_widget)
        self.verticalLayout_16.addWidget(self.horizontal_splitter)
        self.widget = QtGui.QWidget(xrs_integration_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout_24 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_24.setSpacing(8)
        self.horizontalLayout_24.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.mouse_x_lbl = QtGui.QLabel(self.widget)
        self.mouse_x_lbl.setMinimumSize(QtCore.QSize(60, 0))
        self.mouse_x_lbl.setObjectName("mouse_x_lbl")
        self.horizontalLayout_12.addWidget(self.mouse_x_lbl)
        self.mouse_y_lbl = QtGui.QLabel(self.widget)
        self.mouse_y_lbl.setMinimumSize(QtCore.QSize(60, 0))
        self.mouse_y_lbl.setObjectName("mouse_y_lbl")
        self.horizontalLayout_12.addWidget(self.mouse_y_lbl)
        self.mouse_int_lbl = QtGui.QLabel(self.widget)
        self.mouse_int_lbl.setMinimumSize(QtCore.QSize(60, 0))
        self.mouse_int_lbl.setObjectName("mouse_int_lbl")
        self.horizontalLayout_12.addWidget(self.mouse_int_lbl)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.click_x_lbl = QtGui.QLabel(self.widget)
        self.click_x_lbl.setMinimumSize(QtCore.QSize(60, 0))
        self.click_x_lbl.setObjectName("click_x_lbl")
        self.horizontalLayout_13.addWidget(self.click_x_lbl)
        self.click_y_lbl = QtGui.QLabel(self.widget)
        self.click_y_lbl.setMinimumSize(QtCore.QSize(60, 0))
        self.click_y_lbl.setObjectName("click_y_lbl")
        self.horizontalLayout_13.addWidget(self.click_y_lbl)
        self.click_int_lbl = QtGui.QLabel(self.widget)
        self.click_int_lbl.setMinimumSize(QtCore.QSize(60, 0))
        self.click_int_lbl.setObjectName("click_int_lbl")
        self.horizontalLayout_13.addWidget(self.click_int_lbl)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_24.addLayout(self.verticalLayout_4)
        spacerItem12 = QtGui.QSpacerItem(80, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem12)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.mouse_tth_lbl = QtGui.QLabel(self.widget)
        self.mouse_tth_lbl.setMinimumSize(QtCore.QSize(80, 0))
        self.mouse_tth_lbl.setMaximumSize(QtCore.QSize(115, 16777215))
        self.mouse_tth_lbl.setTextFormat(QtCore.Qt.AutoText)
        self.mouse_tth_lbl.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.mouse_tth_lbl.setObjectName("mouse_tth_lbl")
        self.horizontalLayout_28.addWidget(self.mouse_tth_lbl)
        self.mouse_q_lbl = QtGui.QLabel(self.widget)
        self.mouse_q_lbl.setMinimumSize(QtCore.QSize(80, 0))
        self.mouse_q_lbl.setMaximumSize(QtCore.QSize(115, 16777215))
        self.mouse_q_lbl.setTextFormat(QtCore.Qt.AutoText)
        self.mouse_q_lbl.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.mouse_q_lbl.setObjectName("mouse_q_lbl")
        self.horizontalLayout_28.addWidget(self.mouse_q_lbl)
        self.mouse_d_lbl = QtGui.QLabel(self.widget)
        self.mouse_d_lbl.setMinimumSize(QtCore.QSize(80, 0))
        self.mouse_d_lbl.setMaximumSize(QtCore.QSize(115, 16777215))
        self.mouse_d_lbl.setTextFormat(QtCore.Qt.AutoText)
        self.mouse_d_lbl.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.mouse_d_lbl.setObjectName("mouse_d_lbl")
        self.horizontalLayout_28.addWidget(self.mouse_d_lbl)
        self.mouse_azi_lbl = QtGui.QLabel(self.widget)
        self.mouse_azi_lbl.setMinimumSize(QtCore.QSize(80, 0))
        self.mouse_azi_lbl.setMaximumSize(QtCore.QSize(115, 16777215))
        self.mouse_azi_lbl.setTextFormat(QtCore.Qt.AutoText)
        self.mouse_azi_lbl.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.mouse_azi_lbl.setObjectName("mouse_azi_lbl")
        self.horizontalLayout_28.addWidget(self.mouse_azi_lbl)
        self.verticalLayout_3.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.click_tth_lbl = QtGui.QLabel(self.widget)
        self.click_tth_lbl.setMinimumSize(QtCore.QSize(80, 0))
        self.click_tth_lbl.setMaximumSize(QtCore.QSize(115, 16777215))
        self.click_tth_lbl.setTextFormat(QtCore.Qt.AutoText)
        self.click_tth_lbl.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.click_tth_lbl.setObjectName("click_tth_lbl")
        self.horizontalLayout_29.addWidget(self.click_tth_lbl)
        self.click_q_lbl = QtGui.QLabel(self.widget)
        self.click_q_lbl.setMinimumSize(QtCore.QSize(80, 0))
        self.click_q_lbl.setMaximumSize(QtCore.QSize(115, 16777215))
        self.click_q_lbl.setTextFormat(QtCore.Qt.AutoText)
        self.click_q_lbl.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.click_q_lbl.setObjectName("click_q_lbl")
        self.horizontalLayout_29.addWidget(self.click_q_lbl)
        self.click_d_lbl = QtGui.QLabel(self.widget)
        self.click_d_lbl.setMinimumSize(QtCore.QSize(80, 0))
        self.click_d_lbl.setMaximumSize(QtCore.QSize(115, 16777215))
        self.click_d_lbl.setTextFormat(QtCore.Qt.AutoText)
        self.click_d_lbl.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.click_d_lbl.setObjectName("click_d_lbl")
        self.horizontalLayout_29.addWidget(self.click_d_lbl)
        self.click_azi_lbl = QtGui.QLabel(self.widget)
        self.click_azi_lbl.setMinimumSize(QtCore.QSize(80, 0))
        self.click_azi_lbl.setMaximumSize(QtCore.QSize(115, 16777215))
        self.click_azi_lbl.setTextFormat(QtCore.Qt.AutoText)
        self.click_azi_lbl.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.click_azi_lbl.setObjectName("click_azi_lbl")
        self.horizontalLayout_29.addWidget(self.click_azi_lbl)
        self.verticalLayout_3.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_24.addLayout(self.verticalLayout_3)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem13)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        spacerItem14 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem14)
        self.bkg_name_lbl = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bkg_name_lbl.sizePolicy().hasHeightForWidth())
        self.bkg_name_lbl.setSizePolicy(sizePolicy)
        self.bkg_name_lbl.setMinimumSize(QtCore.QSize(0, 19))
        self.bkg_name_lbl.setObjectName("bkg_name_lbl")
        self.verticalLayout_14.addWidget(self.bkg_name_lbl)
        self.horizontalLayout_24.addLayout(self.verticalLayout_14)
        self.verticalLayout_16.addWidget(self.widget)

        self.retranslateUi(xrs_integration_widget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(xrs_integration_widget)

    def retranslateUi(self, xrs_integration_widget):
        xrs_integration_widget.setWindowTitle(
            QtGui.QApplication.translate("xrs_integration_widget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.img_mode_btn.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "Cake", None, QtGui.QApplication.UnicodeUTF8))
        self.img_mask_btn.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "Mask", None, QtGui.QApplication.UnicodeUTF8))
        self.img_autoscale_btn.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "AutoScale", None, QtGui.QApplication.UnicodeUTF8))
        self.load_img_btn.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.prev_img_btn.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.next_img_btn.setText(
            QtGui.QApplication.translate("xrs_integration_widget", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.auto_img_btn.setText(
            QtGui.QApplication.translate("xrs_integration_widget", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.img_browse_by_name_rb.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "By Name", None, QtGui.QApplication.UnicodeUTF8))
        self.img_browse_by_time_rb.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "By Time", None, QtGui.QApplication.UnicodeUTF8))
        self.autoprocess_cb.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "autoprocess", None, QtGui.QApplication.UnicodeUTF8))
        self.img_filename_lbl.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "filename", None, QtGui.QApplication.UnicodeUTF8))
        self.spec_directory_btn_2.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.qa_image_save_img_btn.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "Save Image", None, QtGui.QApplication.UnicodeUTF8))
        self.qa_image_save_spectrum_btn.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "Save Spectrum", None,
                                         QtGui.QApplication.UnicodeUTF8))
        self.qa_image_set_as_overlay_btn.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "As Overlay", None, QtGui.QApplication.UnicodeUTF8))
        self.qa_image_set_as_background_btn.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "As Bkg", None, QtGui.QApplication.UnicodeUTF8))
        self.image_load_calibration_btn.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "Load Calibration", None,
                                         QtGui.QApplication.UnicodeUTF8))
        self.calibration_lbl.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.image_tab),
                                  QtGui.QApplication.translate("xrs_integration_widget", "Img", None,
                                                               QtGui.QApplication.UnicodeUTF8))
        self.spec_load_btn.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.spec_previous_btn.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.spec_next_btn.setText(
            QtGui.QApplication.translate("xrs_integration_widget", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.spec_browse_by_name_rb.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "By Name", None, QtGui.QApplication.UnicodeUTF8))
        self.spec_browse_by_time_rb.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "By Time", None, QtGui.QApplication.UnicodeUTF8))
        self.spec_autocreate_cb.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "autocreate", None, QtGui.QApplication.UnicodeUTF8))
        self.spec_filename_lbl.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "filename", None, QtGui.QApplication.UnicodeUTF8))
        self.spec_directory_btn.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.qa_spectrum_save_spectrum_btn.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "Save Spectrum", None,
                                         QtGui.QApplication.UnicodeUTF8))
        self.qa_spectrum_set_as_overlay_btn.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "As Overlay", None, QtGui.QApplication.UnicodeUTF8))
        self.qa_spectrum_set_as_background_btn.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "As Bkg", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.spectra_tab),
                                  QtGui.QApplication.translate("xrs_integration_widget", "Spec", None,
                                                               QtGui.QApplication.UnicodeUTF8))
        self.overlay_add_btn.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.overlay_del_btn.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.overlay_clear_btn.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "Clear ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "Scale:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "Offset:", None, QtGui.QApplication.UnicodeUTF8))
        self.overlay_show_cb.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "Show", None, QtGui.QApplication.UnicodeUTF8))
        self.overlay_scale_step_txt.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "0.01", None, QtGui.QApplication.UnicodeUTF8))
        self.overlay_offset_step_txt.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "Step", None, QtGui.QApplication.UnicodeUTF8))
        self.overlay_save_set_btn.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "Save Set", None, QtGui.QApplication.UnicodeUTF8))
        self.overlay_load_set_btn.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "Load Set", None, QtGui.QApplication.UnicodeUTF8))
        self.overlay_set_as_bkg_btn.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "Set as Background", None,
                                         QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.overlay_tab),
                                  QtGui.QApplication.translate("xrs_integration_widget", "Overlay", None,
                                                               QtGui.QApplication.UnicodeUTF8))
        self.phase_add_btn.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.phase_edit_btn.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.phase_del_btn.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.phase_clear_btn.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "Step", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "P:", None, QtGui.QApplication.UnicodeUTF8))
        self.phase_pressure_step_txt.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "0.5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "T:", None, QtGui.QApplication.UnicodeUTF8))
        self.phase_temperature_step_txt.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.phase_apply_to_all_cb.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "Apply to all phases", None,
                                         QtGui.QApplication.UnicodeUTF8))
        self.phase_save_set_btn.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "Save Set", None, QtGui.QApplication.UnicodeUTF8))
        self.phase_load_set_btn.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "Load Set", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.phase_tab),
                                  QtGui.QApplication.translate("xrs_integration_widget", "Phase", None,
                                                               QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5),
                                  QtGui.QApplication.translate("xrs_integration_widget", "Bkg", None,
                                                               QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(
            QtGui.QApplication.translate("xrs_integration_widget", "Mask", None, QtGui.QApplication.UnicodeUTF8))
        self.mask_transparent_cb.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "Transparent", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(
            QtGui.QApplication.translate("xrs_integration_widget", "Levels", None, QtGui.QApplication.UnicodeUTF8))
        self.img_levels_autoscale_rb.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "AutoScale", None, QtGui.QApplication.UnicodeUTF8))
        self.img_levels_absolute_rb.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "Absolute", None, QtGui.QApplication.UnicodeUTF8))
        self.img_levels_percentage_rb.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "Percentage", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.special_tab),
                                  QtGui.QApplication.translate("xrs_integration_widget", "X", None,
                                                               QtGui.QApplication.UnicodeUTF8))
        self.spec_tth_btn.setText(
            QtGui.QApplication.translate("xrs_integration_widget", " 2θ", None, QtGui.QApplication.UnicodeUTF8))
        self.spec_q_btn.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "Q", None, QtGui.QApplication.UnicodeUTF8))
        self.spec_d_btn.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "d", None, QtGui.QApplication.UnicodeUTF8))
        self.mouse_x_lbl.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "X:", None, QtGui.QApplication.UnicodeUTF8))
        self.mouse_y_lbl.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.mouse_int_lbl.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "I:", None, QtGui.QApplication.UnicodeUTF8))
        self.click_x_lbl.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "X:", None, QtGui.QApplication.UnicodeUTF8))
        self.click_y_lbl.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.click_int_lbl.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "I:", None, QtGui.QApplication.UnicodeUTF8))
        self.mouse_tth_lbl.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "2θ:", None, QtGui.QApplication.UnicodeUTF8))
        self.mouse_q_lbl.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "Q:", None, QtGui.QApplication.UnicodeUTF8))
        self.mouse_d_lbl.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "d:", None, QtGui.QApplication.UnicodeUTF8))
        self.mouse_azi_lbl.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "χ:", None, QtGui.QApplication.UnicodeUTF8))
        self.click_tth_lbl.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "2θ:", None, QtGui.QApplication.UnicodeUTF8))
        self.click_q_lbl.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "Q:", None, QtGui.QApplication.UnicodeUTF8))
        self.click_d_lbl.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "d:", None, QtGui.QApplication.UnicodeUTF8))
        self.click_azi_lbl.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "χ:", None, QtGui.QApplication.UnicodeUTF8))
        self.bkg_name_lbl.setText(
            QtGui.QApplication.translate("xrs_integration_widget", "Bkg:", None, QtGui.QApplication.UnicodeUTF8))


from pyqtgraph import GraphicsLayoutWidget
