# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Integration.ui'
#
# Created: Fri Jun  6 15:59:23 2014
# by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8

    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_xrs_integration_widget(object):
    def setupUi(self, xrs_integration_widget):
        xrs_integration_widget.setObjectName(_fromUtf8("xrs_integration_widget"))
        xrs_integration_widget.resize(1307, 823)
        xrs_integration_widget.setStyleSheet(_fromUtf8("\n"
                                                       "\n"
                                                       "#image_frame, #spec_container_widget, #spec_btn_widget {\n"
                                                       "    background: black;\n"
                                                       "}\n"
                                                       "#spec_btn_widget QPushButton{\n"
                                                       "    padding: 0px;\n"
                                                       "    padding-right: 1px;\n"
                                                       "    border-radius: 3px;\n"
                                                       "}\n"
                                                       "\n"
                                                       "#spec_btn_widget QPushButton::pressed{\n"
                                                       "    margin: 0px;\n"
                                                       "}"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(xrs_integration_widget)
        self.verticalLayout_16.setSpacing(3)
        self.verticalLayout_16.setMargin(8)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.horizontal_splitter = QtGui.QSplitter(xrs_integration_widget)
        self.horizontal_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.horizontal_splitter.setObjectName(_fromUtf8("horizontal_splitter"))
        self.image_frame = QtGui.QFrame(self.horizontal_splitter)
        self.image_frame.setStyleSheet(_fromUtf8(""))
        self.image_frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.image_frame.setObjectName(_fromUtf8("image_frame"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.image_frame)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.img_pg_layout = GraphicsLayoutWidget(self.image_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_pg_layout.sizePolicy().hasHeightForWidth())
        self.img_pg_layout.setSizePolicy(sizePolicy)
        self.img_pg_layout.setMinimumSize(QtCore.QSize(200, 0))
        self.img_pg_layout.setBaseSize(QtCore.QSize(300, 0))
        self.img_pg_layout.setFrameShape(QtGui.QFrame.StyledPanel)
        self.img_pg_layout.setObjectName(_fromUtf8("img_pg_layout"))
        self.verticalLayout_9.addWidget(self.img_pg_layout)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setSpacing(8)
        self.horizontalLayout_30.setContentsMargins(8, -1, 8, 8)
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.pushButton = QtGui.QPushButton(self.image_frame)
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_30.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(self.image_frame)
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_30.addWidget(self.pushButton_2)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.horizontalLayout_30.addLayout(self.horizontalLayout_25)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem)
        self.pushButton_3 = QtGui.QPushButton(self.image_frame)
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_30.addWidget(self.pushButton_3)
        self.verticalLayout_9.addLayout(self.horizontalLayout_30)
        self.vertical_splitter = QtGui.QSplitter(self.horizontal_splitter)
        self.vertical_splitter.setOrientation(QtCore.Qt.Vertical)
        self.vertical_splitter.setObjectName(_fromUtf8("vertical_splitter"))
        self.tabWidget = QtGui.QTabWidget(self.vertical_splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.image_tab = QtGui.QWidget()
        self.image_tab.setObjectName(_fromUtf8("image_tab"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.image_tab)
        self.verticalLayout_11.setSpacing(8)
        self.verticalLayout_11.setMargin(8)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.frame = QtGui.QFrame(self.image_tab)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setMargin(5)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(8)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.load_img_btn = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_img_btn.sizePolicy().hasHeightForWidth())
        self.load_img_btn.setSizePolicy(sizePolicy)
        self.load_img_btn.setMinimumSize(QtCore.QSize(75, 0))
        self.load_img_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.load_img_btn.setFlat(True)
        self.load_img_btn.setObjectName(_fromUtf8("load_img_btn"))
        self.horizontalLayout_2.addWidget(self.load_img_btn)
        self.prev_img_btn = QtGui.QPushButton(self.frame)
        self.prev_img_btn.setMinimumSize(QtCore.QSize(50, 0))
        self.prev_img_btn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.prev_img_btn.setFlat(True)
        self.prev_img_btn.setObjectName(_fromUtf8("prev_img_btn"))
        self.horizontalLayout_2.addWidget(self.prev_img_btn)
        self.next_img_btn = QtGui.QPushButton(self.frame)
        self.next_img_btn.setMinimumSize(QtCore.QSize(50, 0))
        self.next_img_btn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.next_img_btn.setFlat(True)
        self.next_img_btn.setObjectName(_fromUtf8("next_img_btn"))
        self.horizontalLayout_2.addWidget(self.next_img_btn)
        self.auto_img_btn = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.auto_img_btn.sizePolicy().hasHeightForWidth())
        self.auto_img_btn.setSizePolicy(sizePolicy)
        self.auto_img_btn.setFlat(True)
        self.auto_img_btn.setObjectName(_fromUtf8("auto_img_btn"))
        self.horizontalLayout_2.addWidget(self.auto_img_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.img_browse_by_name_rb = QtGui.QRadioButton(self.frame)
        self.img_browse_by_name_rb.setChecked(True)
        self.img_browse_by_name_rb.setObjectName(_fromUtf8("img_browse_by_name_rb"))
        self.horizontalLayout_17.addWidget(self.img_browse_by_name_rb)
        self.img_browse_by_time_rb = QtGui.QRadioButton(self.frame)
        self.img_browse_by_time_rb.setObjectName(_fromUtf8("img_browse_by_time_rb"))
        self.horizontalLayout_17.addWidget(self.img_browse_by_time_rb)
        self.autoprocess_cb = QtGui.QCheckBox(self.frame)
        self.autoprocess_cb.setAutoExclusive(False)
        self.autoprocess_cb.setTristate(False)
        self.autoprocess_cb.setObjectName(_fromUtf8("autoprocess_cb"))
        self.horizontalLayout_17.addWidget(self.autoprocess_cb)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18.addWidget(self.frame)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.img_filename_lbl = QtGui.QLabel(self.image_tab)
        self.img_filename_lbl.setObjectName(_fromUtf8("img_filename_lbl"))
        self.verticalLayout_10.addWidget(self.img_filename_lbl)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setSpacing(5)
        self.horizontalLayout_26.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.spec_directory_txt_2 = QtGui.QLineEdit(self.image_tab)
        self.spec_directory_txt_2.setMinimumSize(QtCore.QSize(0, 0))
        self.spec_directory_txt_2.setObjectName(_fromUtf8("spec_directory_txt_2"))
        self.horizontalLayout_26.addWidget(self.spec_directory_txt_2)
        self.spec_directory_btn_2 = QtGui.QPushButton(self.image_tab)
        self.spec_directory_btn_2.setFlat(True)
        self.spec_directory_btn_2.setObjectName(_fromUtf8("spec_directory_btn_2"))
        self.horizontalLayout_26.addWidget(self.spec_directory_btn_2)
        self.verticalLayout_10.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_18.addLayout(self.verticalLayout_10)
        self.verticalLayout_11.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setSpacing(5)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.groupBox_3 = QtGui.QGroupBox(self.image_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 43))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_16.setSpacing(8)
        self.horizontalLayout_16.setMargin(8)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.image_rb = QtGui.QRadioButton(self.groupBox_3)
        self.image_rb.setChecked(True)
        self.image_rb.setObjectName(_fromUtf8("image_rb"))
        self.horizontalLayout_16.addWidget(self.image_rb)
        self.cake_rb = QtGui.QRadioButton(self.groupBox_3)
        self.cake_rb.setObjectName(_fromUtf8("cake_rb"))
        self.horizontalLayout_16.addWidget(self.cake_rb)
        self.horizontalLayout_19.addWidget(self.groupBox_3)
        self.groupBox = QtGui.QGroupBox(self.image_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 43))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 50))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_14.setSpacing(14)
        self.horizontalLayout_14.setContentsMargins(8, 8, 13, 8)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.mask_use_cb = QtGui.QCheckBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mask_use_cb.sizePolicy().hasHeightForWidth())
        self.mask_use_cb.setSizePolicy(sizePolicy)
        self.mask_use_cb.setChecked(True)
        self.mask_use_cb.setObjectName(_fromUtf8("mask_use_cb"))
        self.horizontalLayout_14.addWidget(self.mask_use_cb)
        self.mask_transparent_cb = QtGui.QCheckBox(self.groupBox)
        self.mask_transparent_cb.setObjectName(_fromUtf8("mask_transparent_cb"))
        self.horizontalLayout_14.addWidget(self.mask_transparent_cb)
        self.horizontalLayout_19.addWidget(self.groupBox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem1)
        self.verticalLayout_11.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.groupBox_2 = QtGui.QGroupBox(self.image_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 43))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_15.setSpacing(8)
        self.horizontalLayout_15.setMargin(8)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.img_levels_absolute_rb = QtGui.QRadioButton(self.groupBox_2)
        self.img_levels_absolute_rb.setChecked(True)
        self.img_levels_absolute_rb.setObjectName(_fromUtf8("img_levels_absolute_rb"))
        self.horizontalLayout_15.addWidget(self.img_levels_absolute_rb)
        self.img_levels_percentage_rb = QtGui.QRadioButton(self.groupBox_2)
        self.img_levels_percentage_rb.setObjectName(_fromUtf8("img_levels_percentage_rb"))
        self.horizontalLayout_15.addWidget(self.img_levels_percentage_rb)
        self.horizontalLayout_27.addWidget(self.groupBox_2)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem2)
        self.verticalLayout_11.addLayout(self.horizontalLayout_27)
        spacerItem3 = QtGui.QSpacerItem(20, 55, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem3)
        self.widget_2 = QtGui.QWidget(self.image_tab)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_23.setSpacing(-1)
        self.horizontalLayout_23.setMargin(0)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.qa_image_save_img_btn = QtGui.QPushButton(self.widget_2)
        self.qa_image_save_img_btn.setFlat(True)
        self.qa_image_save_img_btn.setObjectName(_fromUtf8("qa_image_save_img_btn"))
        self.horizontalLayout_23.addWidget(self.qa_image_save_img_btn)
        self.qa_image_save_spectrum_btn = QtGui.QPushButton(self.widget_2)
        self.qa_image_save_spectrum_btn.setFlat(True)
        self.qa_image_save_spectrum_btn.setObjectName(_fromUtf8("qa_image_save_spectrum_btn"))
        self.horizontalLayout_23.addWidget(self.qa_image_save_spectrum_btn)
        self.qa_image_set_as_overlay_btn = QtGui.QPushButton(self.widget_2)
        self.qa_image_set_as_overlay_btn.setFlat(True)
        self.qa_image_set_as_overlay_btn.setObjectName(_fromUtf8("qa_image_set_as_overlay_btn"))
        self.horizontalLayout_23.addWidget(self.qa_image_set_as_overlay_btn)
        self.qa_image_set_as_background_btn = QtGui.QPushButton(self.widget_2)
        self.qa_image_set_as_background_btn.setFlat(True)
        self.qa_image_set_as_background_btn.setObjectName(_fromUtf8("qa_image_set_as_background_btn"))
        self.horizontalLayout_23.addWidget(self.qa_image_set_as_background_btn)
        spacerItem4 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem4)
        self.image_load_calibration_btn = QtGui.QPushButton(self.widget_2)
        self.image_load_calibration_btn.setFlat(True)
        self.image_load_calibration_btn.setObjectName(_fromUtf8("image_load_calibration_btn"))
        self.horizontalLayout_23.addWidget(self.image_load_calibration_btn)
        self.calibration_lbl = QtGui.QLabel(self.widget_2)
        self.calibration_lbl.setObjectName(_fromUtf8("calibration_lbl"))
        self.horizontalLayout_23.addWidget(self.calibration_lbl)
        self.verticalLayout_11.addWidget(self.widget_2)
        self.tabWidget.addTab(self.image_tab, _fromUtf8(""))
        self.spectra_tab = QtGui.QWidget()
        self.spectra_tab.setObjectName(_fromUtf8("spectra_tab"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.spectra_tab)
        self.verticalLayout_13.setSpacing(8)
        self.verticalLayout_13.setMargin(8)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.frame_2 = QtGui.QFrame(self.spectra_tab)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setMargin(5)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(8)
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.spec_load_btn = QtGui.QPushButton(self.frame_2)
        self.spec_load_btn.setMinimumSize(QtCore.QSize(75, 0))
        self.spec_load_btn.setMaximumSize(QtCore.QSize(75, 16777215))
        self.spec_load_btn.setFlat(True)
        self.spec_load_btn.setObjectName(_fromUtf8("spec_load_btn"))
        self.horizontalLayout_4.addWidget(self.spec_load_btn)
        self.spec_previous_btn = QtGui.QPushButton(self.frame_2)
        self.spec_previous_btn.setMinimumSize(QtCore.QSize(10, 0))
        self.spec_previous_btn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spec_previous_btn.setFlat(True)
        self.spec_previous_btn.setObjectName(_fromUtf8("spec_previous_btn"))
        self.horizontalLayout_4.addWidget(self.spec_previous_btn)
        self.spec_next_btn = QtGui.QPushButton(self.frame_2)
        self.spec_next_btn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spec_next_btn.setFlat(True)
        self.spec_next_btn.setObjectName(_fromUtf8("spec_next_btn"))
        self.horizontalLayout_4.addWidget(self.spec_next_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.spec_browse_by_name_rb = QtGui.QRadioButton(self.frame_2)
        self.spec_browse_by_name_rb.setChecked(True)
        self.spec_browse_by_name_rb.setObjectName(_fromUtf8("spec_browse_by_name_rb"))
        self.horizontalLayout.addWidget(self.spec_browse_by_name_rb)
        self.spec_browse_by_time_rb = QtGui.QRadioButton(self.frame_2)
        self.spec_browse_by_time_rb.setObjectName(_fromUtf8("spec_browse_by_time_rb"))
        self.horizontalLayout.addWidget(self.spec_browse_by_time_rb)
        self.spec_autocreate_cb = QtGui.QCheckBox(self.frame_2)
        self.spec_autocreate_cb.setChecked(False)
        self.spec_autocreate_cb.setObjectName(_fromUtf8("spec_autocreate_cb"))
        self.horizontalLayout.addWidget(self.spec_autocreate_cb)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_11.addWidget(self.frame_2)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.spec_filename_lbl = QtGui.QLabel(self.spectra_tab)
        self.spec_filename_lbl.setObjectName(_fromUtf8("spec_filename_lbl"))
        self.verticalLayout_12.addWidget(self.spec_filename_lbl)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.spec_directory_txt = QtGui.QLineEdit(self.spectra_tab)
        self.spec_directory_txt.setObjectName(_fromUtf8("spec_directory_txt"))
        self.horizontalLayout_10.addWidget(self.spec_directory_txt)
        self.spec_directory_btn = QtGui.QPushButton(self.spectra_tab)
        self.spec_directory_btn.setFlat(True)
        self.spec_directory_btn.setObjectName(_fromUtf8("spec_directory_btn"))
        self.horizontalLayout_10.addWidget(self.spec_directory_btn)
        self.verticalLayout_12.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11.addLayout(self.verticalLayout_12)
        self.verticalLayout_13.addLayout(self.horizontalLayout_11)
        spacerItem5 = QtGui.QSpacerItem(20, 228, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem5)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.qa_spectrum_save_spectrum_btn = QtGui.QPushButton(self.spectra_tab)
        self.qa_spectrum_save_spectrum_btn.setFlat(True)
        self.qa_spectrum_save_spectrum_btn.setObjectName(_fromUtf8("qa_spectrum_save_spectrum_btn"))
        self.horizontalLayout_22.addWidget(self.qa_spectrum_save_spectrum_btn)
        self.qa_spectrum_set_as_overlay_btn = QtGui.QPushButton(self.spectra_tab)
        self.qa_spectrum_set_as_overlay_btn.setAutoDefault(False)
        self.qa_spectrum_set_as_overlay_btn.setFlat(True)
        self.qa_spectrum_set_as_overlay_btn.setObjectName(_fromUtf8("qa_spectrum_set_as_overlay_btn"))
        self.horizontalLayout_22.addWidget(self.qa_spectrum_set_as_overlay_btn)
        self.qa_spectrum_set_as_background_btn = QtGui.QPushButton(self.spectra_tab)
        self.qa_spectrum_set_as_background_btn.setFlat(True)
        self.qa_spectrum_set_as_background_btn.setObjectName(_fromUtf8("qa_spectrum_set_as_background_btn"))
        self.horizontalLayout_22.addWidget(self.qa_spectrum_set_as_background_btn)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem6)
        self.verticalLayout_13.addLayout(self.horizontalLayout_22)
        self.tabWidget.addTab(self.spectra_tab, _fromUtf8(""))
        self.overlay_tab = QtGui.QWidget()
        self.overlay_tab.setObjectName(_fromUtf8("overlay_tab"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.overlay_tab)
        self.verticalLayout_6.setSpacing(5)
        self.verticalLayout_6.setMargin(5)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.overlay_add_btn = QtGui.QPushButton(self.overlay_tab)
        self.overlay_add_btn.setFlat(True)
        self.overlay_add_btn.setObjectName(_fromUtf8("overlay_add_btn"))
        self.horizontalLayout_3.addWidget(self.overlay_add_btn)
        self.overlay_del_btn = QtGui.QPushButton(self.overlay_tab)
        self.overlay_del_btn.setFlat(True)
        self.overlay_del_btn.setObjectName(_fromUtf8("overlay_del_btn"))
        self.horizontalLayout_3.addWidget(self.overlay_del_btn)
        self.overlay_clear_btn = QtGui.QPushButton(self.overlay_tab)
        self.overlay_clear_btn.setFlat(True)
        self.overlay_clear_btn.setObjectName(_fromUtf8("overlay_clear_btn"))
        self.horizontalLayout_3.addWidget(self.overlay_clear_btn)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.overlay_lw = QtGui.QListWidget(self.overlay_tab)
        self.overlay_lw.setObjectName(_fromUtf8("overlay_lw"))
        self.horizontalLayout_6.addWidget(self.overlay_lw)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSpacing(8)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_3 = QtGui.QLabel(self.overlay_tab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.overlay_scale_sb = QtGui.QDoubleSpinBox(self.overlay_tab)
        self.overlay_scale_sb.setMinimumSize(QtCore.QSize(90, 0))
        self.overlay_scale_sb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.overlay_scale_sb.setDecimals(4)
        self.overlay_scale_sb.setMaximum(999999.0)
        self.overlay_scale_sb.setSingleStep(0.01)
        self.overlay_scale_sb.setObjectName(_fromUtf8("overlay_scale_sb"))
        self.gridLayout.addWidget(self.overlay_scale_sb, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.overlay_tab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.overlay_offset_sb = QtGui.QDoubleSpinBox(self.overlay_tab)
        self.overlay_offset_sb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.overlay_offset_sb.setDecimals(3)
        self.overlay_offset_sb.setMinimum(-999999999.0)
        self.overlay_offset_sb.setMaximum(999999999.0)
        self.overlay_offset_sb.setSingleStep(100.0)
        self.overlay_offset_sb.setProperty("value", 0.0)
        self.overlay_offset_sb.setObjectName(_fromUtf8("overlay_offset_sb"))
        self.gridLayout.addWidget(self.overlay_offset_sb, 2, 1, 1, 1)
        self.overlay_show_cb = QtGui.QCheckBox(self.overlay_tab)
        self.overlay_show_cb.setChecked(True)
        self.overlay_show_cb.setObjectName(_fromUtf8("overlay_show_cb"))
        self.gridLayout.addWidget(self.overlay_show_cb, 3, 0, 1, 3)
        self.overlay_scale_step_txt = QtGui.QLineEdit(self.overlay_tab)
        self.overlay_scale_step_txt.setMaximumSize(QtCore.QSize(80, 16777215))
        self.overlay_scale_step_txt.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.overlay_scale_step_txt.setObjectName(_fromUtf8("overlay_scale_step_txt"))
        self.gridLayout.addWidget(self.overlay_scale_step_txt, 1, 2, 1, 1)
        self.overlay_offset_step_txt = QtGui.QLineEdit(self.overlay_tab)
        self.overlay_offset_step_txt.setMaximumSize(QtCore.QSize(80, 16777215))
        self.overlay_offset_step_txt.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.overlay_offset_step_txt.setObjectName(_fromUtf8("overlay_offset_step_txt"))
        self.gridLayout.addWidget(self.overlay_offset_step_txt, 2, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.overlay_tab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem7)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.overlay_save_set_btn = QtGui.QPushButton(self.overlay_tab)
        self.overlay_save_set_btn.setFlat(True)
        self.overlay_save_set_btn.setObjectName(_fromUtf8("overlay_save_set_btn"))
        self.horizontalLayout_5.addWidget(self.overlay_save_set_btn)
        self.overlay_load_set_btn = QtGui.QPushButton(self.overlay_tab)
        self.overlay_load_set_btn.setFlat(True)
        self.overlay_load_set_btn.setObjectName(_fromUtf8("overlay_load_set_btn"))
        self.horizontalLayout_5.addWidget(self.overlay_load_set_btn)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.overlay_set_as_bkg_btn = QtGui.QPushButton(self.overlay_tab)
        self.overlay_set_as_bkg_btn.setCheckable(True)
        self.overlay_set_as_bkg_btn.setObjectName(_fromUtf8("overlay_set_as_bkg_btn"))
        self.horizontalLayout_5.addWidget(self.overlay_set_as_bkg_btn)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.tabWidget.addTab(self.overlay_tab, _fromUtf8(""))
        self.phase_tab = QtGui.QWidget()
        self.phase_tab.setObjectName(_fromUtf8("phase_tab"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.phase_tab)
        self.verticalLayout_8.setSpacing(5)
        self.verticalLayout_8.setMargin(5)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(8)
        self.horizontalLayout_7.setContentsMargins(8, 0, 8, 0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.phase_add_btn = QtGui.QPushButton(self.phase_tab)
        self.phase_add_btn.setFlat(True)
        self.phase_add_btn.setObjectName(_fromUtf8("phase_add_btn"))
        self.horizontalLayout_7.addWidget(self.phase_add_btn)
        self.phase_edit_btn = QtGui.QPushButton(self.phase_tab)
        self.phase_edit_btn.setFlat(True)
        self.phase_edit_btn.setObjectName(_fromUtf8("phase_edit_btn"))
        self.horizontalLayout_7.addWidget(self.phase_edit_btn)
        self.phase_del_btn = QtGui.QPushButton(self.phase_tab)
        self.phase_del_btn.setFlat(True)
        self.phase_del_btn.setObjectName(_fromUtf8("phase_del_btn"))
        self.horizontalLayout_7.addWidget(self.phase_del_btn)
        self.phase_clear_btn = QtGui.QPushButton(self.phase_tab)
        self.phase_clear_btn.setFlat(True)
        self.phase_clear_btn.setObjectName(_fromUtf8("phase_clear_btn"))
        self.horizontalLayout_7.addWidget(self.phase_clear_btn)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(5)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.phase_lw = QtGui.QListWidget(self.phase_tab)
        self.phase_lw.setObjectName(_fromUtf8("phase_lw"))
        self.horizontalLayout_9.addWidget(self.phase_lw)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setMargin(8)
        self.gridLayout_2.setSpacing(8)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_6 = QtGui.QLabel(self.phase_tab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 2, 1, 1)
        self.label = QtGui.QLabel(self.phase_tab)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.phase_pressure_sb = QtGui.QDoubleSpinBox(self.phase_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phase_pressure_sb.sizePolicy().hasHeightForWidth())
        self.phase_pressure_sb.setSizePolicy(sizePolicy)
        self.phase_pressure_sb.setMinimumSize(QtCore.QSize(110, 0))
        self.phase_pressure_sb.setSizeIncrement(QtCore.QSize(2, 0))
        self.phase_pressure_sb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.phase_pressure_sb.setMinimum(-999999999.0)
        self.phase_pressure_sb.setMaximum(999999999.0)
        self.phase_pressure_sb.setSingleStep(0.5)
        self.phase_pressure_sb.setObjectName(_fromUtf8("phase_pressure_sb"))
        self.gridLayout_2.addWidget(self.phase_pressure_sb, 1, 1, 1, 1)
        self.phase_pressure_step_txt = QtGui.QLineEdit(self.phase_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phase_pressure_step_txt.sizePolicy().hasHeightForWidth())
        self.phase_pressure_step_txt.setSizePolicy(sizePolicy)
        self.phase_pressure_step_txt.setMaximumSize(QtCore.QSize(80, 16777215))
        self.phase_pressure_step_txt.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.phase_pressure_step_txt.setObjectName(_fromUtf8("phase_pressure_step_txt"))
        self.gridLayout_2.addWidget(self.phase_pressure_step_txt, 1, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.phase_tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.phase_temperature_sb = QtGui.QDoubleSpinBox(self.phase_tab)
        self.phase_temperature_sb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.phase_temperature_sb.setMaximum(999999999.0)
        self.phase_temperature_sb.setSingleStep(100.0)
        self.phase_temperature_sb.setObjectName(_fromUtf8("phase_temperature_sb"))
        self.gridLayout_2.addWidget(self.phase_temperature_sb, 2, 1, 1, 1)
        self.phase_temperature_step_txt = QtGui.QLineEdit(self.phase_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phase_temperature_step_txt.sizePolicy().hasHeightForWidth())
        self.phase_temperature_step_txt.setSizePolicy(sizePolicy)
        self.phase_temperature_step_txt.setMaximumSize(QtCore.QSize(80, 16777215))
        self.phase_temperature_step_txt.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.phase_temperature_step_txt.setObjectName(_fromUtf8("phase_temperature_step_txt"))
        self.gridLayout_2.addWidget(self.phase_temperature_step_txt, 2, 2, 1, 1)
        self.phase_apply_to_all_cb = QtGui.QCheckBox(self.phase_tab)
        self.phase_apply_to_all_cb.setChecked(True)
        self.phase_apply_to_all_cb.setObjectName(_fromUtf8("phase_apply_to_all_cb"))
        self.gridLayout_2.addWidget(self.phase_apply_to_all_cb, 3, 0, 1, 3)
        self.verticalLayout_7.addLayout(self.gridLayout_2)
        spacerItem9 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem9)
        self.horizontalLayout_9.addLayout(self.verticalLayout_7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(8)
        self.horizontalLayout_8.setMargin(8)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.phase_save_set_btn = QtGui.QPushButton(self.phase_tab)
        self.phase_save_set_btn.setFlat(True)
        self.phase_save_set_btn.setObjectName(_fromUtf8("phase_save_set_btn"))
        self.horizontalLayout_8.addWidget(self.phase_save_set_btn)
        self.phase_load_set_btn = QtGui.QPushButton(self.phase_tab)
        self.phase_load_set_btn.setFlat(True)
        self.phase_load_set_btn.setObjectName(_fromUtf8("phase_load_set_btn"))
        self.horizontalLayout_8.addWidget(self.phase_load_set_btn)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem10)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.tabWidget.addTab(self.phase_tab, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.special_tab = QtGui.QWidget()
        self.special_tab.setObjectName(_fromUtf8("special_tab"))
        self.tabWidget.addTab(self.special_tab, _fromUtf8(""))
        self.spec_container_widget = QtGui.QWidget(self.vertical_splitter)
        self.spec_container_widget.setObjectName(_fromUtf8("spec_container_widget"))
        self.horizontalLayout_31 = QtGui.QHBoxLayout(self.spec_container_widget)
        self.horizontalLayout_31.setSpacing(0)
        self.horizontalLayout_31.setMargin(0)
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.spectrum_pg_layout = GraphicsLayoutWidget(self.spec_container_widget)
        self.spectrum_pg_layout.setSizeIncrement(QtCore.QSize(1, 2))
        self.spectrum_pg_layout.setBaseSize(QtCore.QSize(300, 300))
        self.spectrum_pg_layout.setFrameShape(QtGui.QFrame.StyledPanel)
        self.spectrum_pg_layout.setFrameShadow(QtGui.QFrame.Sunken)
        self.spectrum_pg_layout.setObjectName(_fromUtf8("spectrum_pg_layout"))
        self.horizontalLayout_31.addWidget(self.spectrum_pg_layout)
        self.spec_btn_widget = QtGui.QWidget(self.spec_container_widget)
        self.spec_btn_widget.setObjectName(_fromUtf8("spec_btn_widget"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.spec_btn_widget)
        self.verticalLayout_15.setSpacing(4)
        self.verticalLayout_15.setContentsMargins(0, 4, 4, 0)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.spec_tth_btn = QtGui.QPushButton(self.spec_btn_widget)
        self.spec_tth_btn.setCheckable(True)
        self.spec_tth_btn.setChecked(True)
        self.spec_tth_btn.setFlat(True)
        self.spec_tth_btn.setObjectName(_fromUtf8("spec_tth_btn"))
        self.verticalLayout_15.addWidget(self.spec_tth_btn)
        self.spec_q_btn = QtGui.QPushButton(self.spec_btn_widget)
        self.spec_q_btn.setCheckable(True)
        self.spec_q_btn.setFlat(True)
        self.spec_q_btn.setObjectName(_fromUtf8("spec_q_btn"))
        self.verticalLayout_15.addWidget(self.spec_q_btn)
        self.spec_d_btn = QtGui.QPushButton(self.spec_btn_widget)
        self.spec_d_btn.setCheckable(True)
        self.spec_d_btn.setFlat(True)
        self.spec_d_btn.setObjectName(_fromUtf8("spec_d_btn"))
        self.verticalLayout_15.addWidget(self.spec_d_btn)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem11)
        self.horizontalLayout_31.addWidget(self.spec_btn_widget)
        self.verticalLayout_16.addWidget(self.horizontal_splitter)
        self.widget = QtGui.QWidget(xrs_integration_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_24.setSpacing(8)
        self.horizontalLayout_24.setMargin(8)
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.mouse_x_lbl = QtGui.QLabel(self.widget)
        self.mouse_x_lbl.setMinimumSize(QtCore.QSize(60, 0))
        self.mouse_x_lbl.setObjectName(_fromUtf8("mouse_x_lbl"))
        self.horizontalLayout_12.addWidget(self.mouse_x_lbl)
        self.mouse_y_lbl = QtGui.QLabel(self.widget)
        self.mouse_y_lbl.setMinimumSize(QtCore.QSize(60, 0))
        self.mouse_y_lbl.setObjectName(_fromUtf8("mouse_y_lbl"))
        self.horizontalLayout_12.addWidget(self.mouse_y_lbl)
        self.mouse_int_lbl = QtGui.QLabel(self.widget)
        self.mouse_int_lbl.setMinimumSize(QtCore.QSize(60, 0))
        self.mouse_int_lbl.setObjectName(_fromUtf8("mouse_int_lbl"))
        self.horizontalLayout_12.addWidget(self.mouse_int_lbl)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.click_x_lbl = QtGui.QLabel(self.widget)
        self.click_x_lbl.setMinimumSize(QtCore.QSize(60, 0))
        self.click_x_lbl.setObjectName(_fromUtf8("click_x_lbl"))
        self.horizontalLayout_13.addWidget(self.click_x_lbl)
        self.click_y_lbl = QtGui.QLabel(self.widget)
        self.click_y_lbl.setMinimumSize(QtCore.QSize(60, 0))
        self.click_y_lbl.setObjectName(_fromUtf8("click_y_lbl"))
        self.horizontalLayout_13.addWidget(self.click_y_lbl)
        self.click_int_lbl = QtGui.QLabel(self.widget)
        self.click_int_lbl.setMinimumSize(QtCore.QSize(60, 0))
        self.click_int_lbl.setObjectName(_fromUtf8("click_int_lbl"))
        self.horizontalLayout_13.addWidget(self.click_int_lbl)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_24.addLayout(self.verticalLayout_4)
        spacerItem12 = QtGui.QSpacerItem(80, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem12)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.mouse_tth_lbl = QtGui.QLabel(self.widget)
        self.mouse_tth_lbl.setMinimumSize(QtCore.QSize(80, 0))
        self.mouse_tth_lbl.setMaximumSize(QtCore.QSize(115, 16777215))
        self.mouse_tth_lbl.setTextFormat(QtCore.Qt.AutoText)
        self.mouse_tth_lbl.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.mouse_tth_lbl.setObjectName(_fromUtf8("mouse_tth_lbl"))
        self.horizontalLayout_28.addWidget(self.mouse_tth_lbl)
        self.mouse_q_lbl = QtGui.QLabel(self.widget)
        self.mouse_q_lbl.setMinimumSize(QtCore.QSize(80, 0))
        self.mouse_q_lbl.setMaximumSize(QtCore.QSize(115, 16777215))
        self.mouse_q_lbl.setTextFormat(QtCore.Qt.AutoText)
        self.mouse_q_lbl.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.mouse_q_lbl.setObjectName(_fromUtf8("mouse_q_lbl"))
        self.horizontalLayout_28.addWidget(self.mouse_q_lbl)
        self.mouse_d_lbl = QtGui.QLabel(self.widget)
        self.mouse_d_lbl.setMinimumSize(QtCore.QSize(80, 0))
        self.mouse_d_lbl.setMaximumSize(QtCore.QSize(115, 16777215))
        self.mouse_d_lbl.setTextFormat(QtCore.Qt.AutoText)
        self.mouse_d_lbl.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.mouse_d_lbl.setObjectName(_fromUtf8("mouse_d_lbl"))
        self.horizontalLayout_28.addWidget(self.mouse_d_lbl)
        self.mouse_azi_lbl = QtGui.QLabel(self.widget)
        self.mouse_azi_lbl.setMinimumSize(QtCore.QSize(80, 0))
        self.mouse_azi_lbl.setMaximumSize(QtCore.QSize(115, 16777215))
        self.mouse_azi_lbl.setTextFormat(QtCore.Qt.AutoText)
        self.mouse_azi_lbl.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.mouse_azi_lbl.setObjectName(_fromUtf8("mouse_azi_lbl"))
        self.horizontalLayout_28.addWidget(self.mouse_azi_lbl)
        self.verticalLayout_3.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.click_tth_lbl = QtGui.QLabel(self.widget)
        self.click_tth_lbl.setMinimumSize(QtCore.QSize(80, 0))
        self.click_tth_lbl.setMaximumSize(QtCore.QSize(115, 16777215))
        self.click_tth_lbl.setTextFormat(QtCore.Qt.AutoText)
        self.click_tth_lbl.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.click_tth_lbl.setObjectName(_fromUtf8("click_tth_lbl"))
        self.horizontalLayout_29.addWidget(self.click_tth_lbl)
        self.click_q_lbl = QtGui.QLabel(self.widget)
        self.click_q_lbl.setMinimumSize(QtCore.QSize(80, 0))
        self.click_q_lbl.setMaximumSize(QtCore.QSize(115, 16777215))
        self.click_q_lbl.setTextFormat(QtCore.Qt.AutoText)
        self.click_q_lbl.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.click_q_lbl.setObjectName(_fromUtf8("click_q_lbl"))
        self.horizontalLayout_29.addWidget(self.click_q_lbl)
        self.click_d_lbl = QtGui.QLabel(self.widget)
        self.click_d_lbl.setMinimumSize(QtCore.QSize(80, 0))
        self.click_d_lbl.setMaximumSize(QtCore.QSize(115, 16777215))
        self.click_d_lbl.setTextFormat(QtCore.Qt.AutoText)
        self.click_d_lbl.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.click_d_lbl.setObjectName(_fromUtf8("click_d_lbl"))
        self.horizontalLayout_29.addWidget(self.click_d_lbl)
        self.click_azi_lbl = QtGui.QLabel(self.widget)
        self.click_azi_lbl.setMinimumSize(QtCore.QSize(80, 0))
        self.click_azi_lbl.setMaximumSize(QtCore.QSize(115, 16777215))
        self.click_azi_lbl.setTextFormat(QtCore.Qt.AutoText)
        self.click_azi_lbl.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.click_azi_lbl.setObjectName(_fromUtf8("click_azi_lbl"))
        self.horizontalLayout_29.addWidget(self.click_azi_lbl)
        self.verticalLayout_3.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_24.addLayout(self.verticalLayout_3)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem13)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        spacerItem14 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem14)
        self.bkg_name_lbl = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bkg_name_lbl.sizePolicy().hasHeightForWidth())
        self.bkg_name_lbl.setSizePolicy(sizePolicy)
        self.bkg_name_lbl.setMinimumSize(QtCore.QSize(0, 19))
        self.bkg_name_lbl.setObjectName(_fromUtf8("bkg_name_lbl"))
        self.verticalLayout_14.addWidget(self.bkg_name_lbl)
        self.horizontalLayout_24.addLayout(self.verticalLayout_14)
        self.verticalLayout_16.addWidget(self.widget)

        self.retranslateUi(xrs_integration_widget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(xrs_integration_widget)

    def retranslateUi(self, xrs_integration_widget):
        xrs_integration_widget.setWindowTitle(_translate("xrs_integration_widget", "Form", None))
        self.pushButton.setText(_translate("xrs_integration_widget", "Image", None))
        self.pushButton_2.setText(_translate("xrs_integration_widget", "Mask", None))
        self.pushButton_3.setText(_translate("xrs_integration_widget", "AutoScale", None))
        self.load_img_btn.setText(_translate("xrs_integration_widget", "Load", None))
        self.prev_img_btn.setText(_translate("xrs_integration_widget", "<", None))
        self.next_img_btn.setText(_translate("xrs_integration_widget", ">", None))
        self.auto_img_btn.setText(_translate("xrs_integration_widget", ">>", None))
        self.img_browse_by_name_rb.setText(_translate("xrs_integration_widget", "By Name", None))
        self.img_browse_by_time_rb.setText(_translate("xrs_integration_widget", "By Time", None))
        self.autoprocess_cb.setText(_translate("xrs_integration_widget", "autoprocess", None))
        self.img_filename_lbl.setText(_translate("xrs_integration_widget", "filename", None))
        self.spec_directory_btn_2.setText(_translate("xrs_integration_widget", "...", None))
        self.groupBox_3.setTitle(_translate("xrs_integration_widget", "Show", None))
        self.image_rb.setText(_translate("xrs_integration_widget", "Image", None))
        self.cake_rb.setText(_translate("xrs_integration_widget", "Cake", None))
        self.groupBox.setTitle(_translate("xrs_integration_widget", "Mask", None))
        self.mask_use_cb.setText(_translate("xrs_integration_widget", "Use", None))
        self.mask_transparent_cb.setText(_translate("xrs_integration_widget", "Transparent", None))
        self.groupBox_2.setTitle(_translate("xrs_integration_widget", "Levels", None))
        self.img_levels_absolute_rb.setText(_translate("xrs_integration_widget", "Absolute", None))
        self.img_levels_percentage_rb.setText(_translate("xrs_integration_widget", "Percentage", None))
        self.qa_image_save_img_btn.setText(_translate("xrs_integration_widget", "Save Image", None))
        self.qa_image_save_spectrum_btn.setText(_translate("xrs_integration_widget", "Save Spectrum", None))
        self.qa_image_set_as_overlay_btn.setText(_translate("xrs_integration_widget", "As Overlay", None))
        self.qa_image_set_as_background_btn.setText(_translate("xrs_integration_widget", "As Bkg", None))
        self.image_load_calibration_btn.setText(_translate("xrs_integration_widget", "Load Calibration", None))
        self.calibration_lbl.setText(_translate("xrs_integration_widget", "None", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.image_tab),
                                  _translate("xrs_integration_widget", "Img", None))
        self.spec_load_btn.setText(_translate("xrs_integration_widget", "Load", None))
        self.spec_previous_btn.setText(_translate("xrs_integration_widget", "<", None))
        self.spec_next_btn.setText(_translate("xrs_integration_widget", ">", None))
        self.spec_browse_by_name_rb.setText(_translate("xrs_integration_widget", "By Name", None))
        self.spec_browse_by_time_rb.setText(_translate("xrs_integration_widget", "By Time", None))
        self.spec_autocreate_cb.setText(_translate("xrs_integration_widget", "autocreate", None))
        self.spec_filename_lbl.setText(_translate("xrs_integration_widget", "filename", None))
        self.spec_directory_btn.setText(_translate("xrs_integration_widget", "...", None))
        self.qa_spectrum_save_spectrum_btn.setText(_translate("xrs_integration_widget", "Save Spectrum", None))
        self.qa_spectrum_set_as_overlay_btn.setText(_translate("xrs_integration_widget", "As Overlay", None))
        self.qa_spectrum_set_as_background_btn.setText(_translate("xrs_integration_widget", "As Bkg", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.spectra_tab),
                                  _translate("xrs_integration_widget", "Spec", None))
        self.overlay_add_btn.setText(_translate("xrs_integration_widget", "Add", None))
        self.overlay_del_btn.setText(_translate("xrs_integration_widget", "Delete", None))
        self.overlay_clear_btn.setText(_translate("xrs_integration_widget", "Clear ", None))
        self.label_3.setText(_translate("xrs_integration_widget", "Scale:", None))
        self.label_4.setText(_translate("xrs_integration_widget", "Offset:", None))
        self.overlay_show_cb.setText(_translate("xrs_integration_widget", "Show", None))
        self.overlay_scale_step_txt.setText(_translate("xrs_integration_widget", "0.01", None))
        self.overlay_offset_step_txt.setText(_translate("xrs_integration_widget", "100", None))
        self.label_5.setText(_translate("xrs_integration_widget", "Step", None))
        self.overlay_save_set_btn.setText(_translate("xrs_integration_widget", "Save Set", None))
        self.overlay_load_set_btn.setText(_translate("xrs_integration_widget", "Load Set", None))
        self.overlay_set_as_bkg_btn.setText(_translate("xrs_integration_widget", "Set as Background", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.overlay_tab),
                                  _translate("xrs_integration_widget", "Overlay", None))
        self.phase_add_btn.setText(_translate("xrs_integration_widget", "Add", None))
        self.phase_edit_btn.setText(_translate("xrs_integration_widget", "Edit", None))
        self.phase_del_btn.setText(_translate("xrs_integration_widget", "Delete", None))
        self.phase_clear_btn.setText(_translate("xrs_integration_widget", "Clear", None))
        self.label_6.setText(_translate("xrs_integration_widget", "Step", None))
        self.label.setText(_translate("xrs_integration_widget", "P:", None))
        self.phase_pressure_step_txt.setText(_translate("xrs_integration_widget", "0.5", None))
        self.label_2.setText(_translate("xrs_integration_widget", "T:", None))
        self.phase_temperature_step_txt.setText(_translate("xrs_integration_widget", "100", None))
        self.phase_apply_to_all_cb.setText(_translate("xrs_integration_widget", "Apply to all phases", None))
        self.phase_save_set_btn.setText(_translate("xrs_integration_widget", "Save Set", None))
        self.phase_load_set_btn.setText(_translate("xrs_integration_widget", "Load Set", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.phase_tab),
                                  _translate("xrs_integration_widget", "Phase", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("xrs_integration_widget", "Bkg", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.special_tab),
                                  _translate("xrs_integration_widget", "X", None))
        self.spec_tth_btn.setText(_translate("xrs_integration_widget", " 2θ", None))
        self.spec_q_btn.setText(_translate("xrs_integration_widget", "Q", None))
        self.spec_d_btn.setText(_translate("xrs_integration_widget", "d", None))
        self.mouse_x_lbl.setText(_translate("xrs_integration_widget", "X:", None))
        self.mouse_y_lbl.setText(_translate("xrs_integration_widget", "Y:", None))
        self.mouse_int_lbl.setText(_translate("xrs_integration_widget", "I:", None))
        self.click_x_lbl.setText(_translate("xrs_integration_widget", "X:", None))
        self.click_y_lbl.setText(_translate("xrs_integration_widget", "Y:", None))
        self.click_int_lbl.setText(_translate("xrs_integration_widget", "I:", None))
        self.mouse_tth_lbl.setText(_translate("xrs_integration_widget", "2θ:", None))
        self.mouse_q_lbl.setText(_translate("xrs_integration_widget", "Q:", None))
        self.mouse_d_lbl.setText(_translate("xrs_integration_widget", "d:", None))
        self.mouse_azi_lbl.setText(_translate("xrs_integration_widget", "χ:", None))
        self.click_tth_lbl.setText(_translate("xrs_integration_widget", "2θ:", None))
        self.click_q_lbl.setText(_translate("xrs_integration_widget", "Q:", None))
        self.click_d_lbl.setText(_translate("xrs_integration_widget", "d:", None))
        self.click_azi_lbl.setText(_translate("xrs_integration_widget", "χ:", None))
        self.bkg_name_lbl.setText(_translate("xrs_integration_widget", "Bkg:", None))


from pyqtgraph import GraphicsLayoutWidget
