# SPDX-License-Identifier: MIT
"""
EoS material format utilities.

Provides:
- build_jcpds(material, eos)        -> jcpds object ready for Dioptas
- write_eosmat(path, material, eos) -> .eosmat file (see format below)
- read_eosmat(path)                 -> (material_dict, eos_dict) parsed back

The .eosmat format
-------------------
A plain-text, line-oriented format: one ``KEY value`` pair per line, plus
a single comment header documenting the diffraction-peak table that
follows. Unlike JCPDS's ``DIHKL`` lines, the peak keyword is not repeated
for every row — one comment line explains the column order once, and the
peaks themselves are just whitespace-separated numbers. Unlike TOML, there
are no bracketed sections — every line is either a comment (#), a
key/value pair, or (after the peak header) a bare data row.

Example
-------
# EoS Material File - Gold (Au)
# Generated by Dioptas / EoS Database - 2026-06-23
# EoS reference: Fei et al. 2007

NAME       Gold
FORMULA    Au
SPACEGROUP CUBIC
A          4.0786   # Å
B          4.0786   # Å
C          4.0786   # Å

EOS_TYPE   Birch-Murnaghan
REFERENCE  Fei et al. 2007
V0         67.850   # Å³
K0         167.0    # GPa
K0_PRIME   6.0

# Diffraction peaks: h  k  l  d(Å)  intensity
1  1  1  2.3550  100.0
2  0  0  2.0393   52.0
"""

from __future__ import annotations

import datetime
from typing import Optional, Dict, List, Tuple


def eos_engine_type(eos: Dict) -> str:
    """
    Map a database EoS record to the engine type understood by EosPhase /
    jcpds (one of BM2, BM3, VINET, HOLZAPFEL).

    The database stores ``eos_type`` as a human label ("Birch-Murnaghan",
    "Vinet", "Holzapfel") plus an ``eos_order`` (2/3) for Birch-Murnaghan.
    """
    label = (eos.get("eos_type") or "").lower()
    if "vinet" in label:
        return "VINET"
    if "holzapfel" in label:
        return "HOLZAPFEL"
    # Birch-Murnaghan (or unknown) — distinguish 2nd vs 3rd order
    if eos.get("eos_order") == 2:
        return "BM2"
    return "BM3"


# ---------------------------------------------------------------------------
# jcpds object builder (unchanged — used regardless of save format)
# ---------------------------------------------------------------------------

def build_jcpds(material: Dict, eos: Optional[Dict] = None):
    """
    Build a Dioptas ``jcpds`` object from database material + EoS dicts.

    Parameters
    ----------
    material : dict
        Full material record (with ``diffraction_peaks`` list) from the API.
    eos : dict, optional
        EoS parameter record from the API.

    Returns
    -------
    jcpds
        Ready-to-use object accepted by ``PhaseModel.add_jcpds_object``.
    """
    from .model.util.jcpds import jcpds, jcpds_reflection

    obj = jcpds()
    name = material.get("name") or material.get("formula", "unknown")
    obj._name = name
    obj._filename = f"<EoS DB: {name}>"

    obj.params["symmetry"] = (material.get("symmetry") or "").upper()
    a = float(material.get("a") or 0)
    b = float(material.get("b") or 0) or a
    c = float(material.get("c") or 0) or a
    obj.params["a0"] = a
    obj.params["b0"] = b
    obj.params["c0"] = c
    obj.params["alpha0"] = float(material.get("alpha") or 90)
    obj.params["beta0"]  = float(material.get("beta")  or 90)
    obj.params["gamma0"] = float(material.get("gamma") or 90)
    for key in ("a", "b", "c", "alpha", "beta", "gamma"):
        obj.params[key] = obj.params[f"{key}0"]

    if eos:
        obj.params["k0"]       = float(eos.get("k0")        or 0)
        obj.params["k0p0"]     = float(eos.get("k0_prime")  or 0)
        obj.params["k0p"]      = obj.params["k0p0"]
        obj.params["alpha_t0"] = float(eos.get("alpha0")    or 0)
        obj.params["dk0dt"]    = float(eos.get("dK_dT")     or 0)
        # Tell the live engine which EoS to use for volume-at-pressure.
        obj.params["eos_type"] = eos_engine_type(eos)
        if eos.get("n") is not None:
            obj.params["n"] = float(eos["n"])
        if eos.get("Z") is not None:
            obj.params["z"] = int(eos["Z"])
        v0 = eos.get("v0")
        if v0:
            obj.params["v0"] = float(v0)
            obj.params["v"]  = float(v0)

    for peak in material.get("diffraction_peaks", []):
        refl = jcpds_reflection(
            h=int(peak.get("h", 0)),
            k=int(peak.get("k", 0)),
            l=int(peak.get("l", 0)),
            intensity=float(peak.get("intensity", 0)),
            d=float(peak.get("d_spacing", 0)),
        )
        obj.reflections.append(refl)

    obj.params["modified"] = False
    return obj


# ---------------------------------------------------------------------------
# .eosmat writer
# ---------------------------------------------------------------------------

def write_eosmat(path: str, material: Dict, eos: Optional[Dict] = None) -> None:
    """Write a compact, comment-documented ``.eosmat`` file."""
    name    = material.get("name") or material.get("formula", "unknown")
    formula = material.get("formula", "")
    today   = datetime.date.today().isoformat()

    lines: List[str] = [
        f"# EoS Material File - {name} ({formula})",
        f"# Generated by Dioptas / EoS Database - {today}",
    ]
    if eos and eos.get("reference"):
        lines.append(f"# EoS reference: {eos['reference']}")
    lines.append("")

    lines.append(f"NAME       {name}")
    lines.append(f"FORMULA    {formula}")
    lines.append(f'SPACEGROUP {material.get("symmetry", "")}')
    lines.append(f'A          {_num(material.get("a"))}   # Å')
    lines.append(f'B          {_num(material.get("b"))}   # Å')
    lines.append(f'C          {_num(material.get("c"))}   # Å')
    if material.get("notes"):
        lines.append(f'NOTES      {material["notes"]}')
    lines.append("")

    if eos:
        lines.append(f'EOS_TYPE   {eos.get("eos_type", "")}')
        if eos.get("eos_order") is not None:
            lines.append(f'EOS_ORDER  {eos.get("eos_order")}')
        lines.append(f'REFERENCE  {eos.get("reference") or ""}')
        lines.append(f'V0         {_num(eos.get("v0"))}   # Å³')
        lines.append(f'K0         {_num(eos.get("k0"))}   # GPa')
        lines.append(f'K0_PRIME   {_num(eos.get("k0_prime"))}')
        if eos.get("alpha0") is not None:
            lines.append(f'ALPHA_T    {_num(eos["alpha0"])}  # K⁻¹')
        if eos.get("dK_dT") is not None:
            lines.append(f'DK_DT      {_num(eos["dK_dT"])}  # GPa K⁻¹')
        if eos.get("reference_temperature") is not None:
            lines.append(f'T_REF      {_num(eos["reference_temperature"])}  # K')
        lines.append("")

    peaks = material.get("diffraction_peaks", [])
    if peaks:
        lines.append("# Diffraction peaks: h  k  l  d(Å)  intensity")
        for pk in peaks:
            lines.append(
                f'{pk.get("h", 0)}  {pk.get("k", 0)}  {pk.get("l", 0)}  '
                f'{float(pk.get("d_spacing", 0)):.4f}  '
                f'{float(pk.get("intensity", 0)):.1f}'
            )

    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")


# ---------------------------------------------------------------------------
# .eosmat reader
# ---------------------------------------------------------------------------

def read_eosmat(path: str) -> Tuple[Dict, Optional[Dict]]:
    """
    Parse a ``.eosmat`` file back into ``(material_dict, eos_dict)``,
    in the same shape the database API returns, so the result can be fed
    straight into ``build_jcpds()``.
    """
    material: Dict = {"diffraction_peaks": []}
    eos: Dict = {}
    in_peaks = False

    with open(path, "r", encoding="utf-8") as fh:
        for raw_line in fh:
            line = raw_line.split("#", 1)[0].strip()
            is_comment_line = raw_line.strip().startswith("#")

            if is_comment_line and "peak" in raw_line.lower():
                in_peaks = True
                continue
            if not line:
                continue

            if in_peaks:
                parts = line.split()
                if len(parts) >= 5:
                    h, k, l, d, intensity = parts[:5]
                    material["diffraction_peaks"].append({
                        "h": int(float(h)), "k": int(float(k)), "l": int(float(l)),
                        "d_spacing": float(d), "intensity": float(intensity),
                    })
                continue

            key, _, value = line.partition(" ")
            key = key.strip().upper()
            value = value.strip()
            if not key:
                continue

            if key in ("NAME", "FORMULA", "NOTES"):
                material[key.lower()] = value
            elif key == "SPACEGROUP":
                material["symmetry"] = value
            elif key in ("A", "B", "C"):
                material[key.lower()] = float(value)
            elif key == "EOS_TYPE":
                eos["eos_type"] = value
            elif key == "EOS_ORDER":
                eos["eos_order"] = int(float(value))
            elif key == "REFERENCE":
                eos["reference"] = value
            elif key == "V0":
                eos["v0"] = float(value)
            elif key == "K0":
                eos["k0"] = float(value)
            elif key == "K0_PRIME":
                eos["k0_prime"] = float(value)
            elif key == "ALPHA_T":
                eos["alpha0"] = float(value)
            elif key == "DK_DT":
                eos["dK_dT"] = float(value)
            elif key == "T_REF":
                eos["reference_temperature"] = float(value)

    return material, (eos or None)


def _num(value) -> str:
    if value is None:
        return "0"
    try:
        return f"{float(value)}"
    except (TypeError, ValueError):
        return str(value)
