# SPDX-License-Identifier: MIT
"""
EoS material format utilities.

Provides:
- build_jcpds(material, eos)   → jcpds object ready for Dioptas
- write_eosmat(path, material, eos)  → TOML-based .eosmat file with comments

The .eosmat format is a TOML file (human-readable, supports # comments)
that stores full material + EoS + diffraction-peak data. It is designed as
a richer, self-documenting alternative to the legacy JCPDS text format.

Example .eosmat file
--------------------
# EoS Material File — generated by Dioptas / EoS Database
# Reference: Fei et al. (2007) Phys. Earth Planet. Inter. 143–144

[material]
name     = "Gold"
formula  = "Au"
symmetry = "CUBIC"
a        = 4.0786   # Å — lattice parameter
b        = 4.0786   # Å
c        = 4.0786   # Å
alpha    = 90.0     # °
beta     = 90.0     # °
gamma    = 90.0     # °

[eos]
type      = "Birch-Murnaghan"  # BM2 | BM3 | BM4 | Vinet | Holzapfel
order     = 3
reference = "Fei et al. 2007"
v0        = 67.850   # Å³ — zero-pressure volume
k0        = 167.0    # GPa — zero-pressure bulk modulus
k0_prime  = 6.0      # dK/dP (dimensionless)
alpha_t   = 4.26e-5  # K⁻¹ — thermal expansion coefficient
dK_dT     = -0.016   # GPa K⁻¹ — temperature derivative of K0
t_ref     = 298.15   # K — reference temperature

[[peaks]]
h = 1; k = 1; l = 1; d = 2.355; intensity = 100.0
...
"""

from __future__ import annotations

import datetime
import textwrap
from typing import Optional, Dict, List, Any


# ---------------------------------------------------------------------------
# jcpds object builder
# ---------------------------------------------------------------------------

def build_jcpds(material: Dict, eos: Optional[Dict] = None):
    """
    Build a Dioptas ``jcpds`` object from database material + EoS dicts.

    Parameters
    ----------
    material : dict
        Full material record (with ``diffraction_peaks`` list) from the API.
    eos : dict, optional
        EoS parameter record from the API.  The first available EoS is used
        when *None* is supplied.

    Returns
    -------
    jcpds
        Ready-to-use object accepted by ``PhaseModel.add_jcpds_object``.
    """
    from .model.util.jcpds import jcpds, jcpds_reflection

    obj = jcpds()
    name = material.get("name") or material.get("formula", "unknown")
    obj._name = name
    obj._filename = f"<EoS DB: {name}>"

    # Lattice parameters
    obj.params["symmetry"] = (material.get("symmetry") or "").upper()
    a = float(material.get("a") or 0)
    b = float(material.get("b") or 0) or a
    c = float(material.get("c") or 0) or a
    obj.params["a0"] = a
    obj.params["b0"] = b
    obj.params["c0"] = c
    obj.params["alpha0"] = float(material.get("alpha") or 90)
    obj.params["beta0"]  = float(material.get("beta")  or 90)
    obj.params["gamma0"] = float(material.get("gamma") or 90)
    # Mirror to current lattice
    for key in ("a", "b", "c", "alpha", "beta", "gamma"):
        obj.params[key] = obj.params[f"{key}0"]

    # EoS parameters
    if eos:
        obj.params["k0"]       = float(eos.get("k0")        or 0)
        obj.params["k0p0"]     = float(eos.get("k0_prime")  or 0)
        obj.params["k0p"]      = obj.params["k0p0"]
        obj.params["alpha_t0"] = float(eos.get("alpha0")    or 0)
        obj.params["dk0dt"]    = float(eos.get("dK_dT")     or 0)
        v0 = eos.get("v0")
        if v0:
            obj.params["v0"] = float(v0)
            obj.params["v"]  = float(v0)

    # Diffraction peaks
    for peak in material.get("diffraction_peaks", []):
        refl = jcpds_reflection(
            h=int(peak.get("h", 0)),
            k=int(peak.get("k", 0)),
            l=int(peak.get("l", 0)),
            intensity=float(peak.get("intensity", 0)),
            d=float(peak.get("d_spacing", 0)),
        )
        obj.reflections.append(refl)

    obj.params["modified"] = False
    return obj


# ---------------------------------------------------------------------------
# TOML / .eosmat writer
# ---------------------------------------------------------------------------

def write_eosmat(path: str, material: Dict, eos: Optional[Dict] = None) -> None:
    """
    Write a human-readable TOML ``.eosmat`` file for the given material.

    The format supports ``#`` comments, making it far more self-documenting
    than legacy JCPDS files or plain JSON.

    Parameters
    ----------
    path : str
        Destination file path (should end in ``.eosmat``).
    material : dict
        Full material record from the API.
    eos : dict, optional
        EoS parameter record.  When omitted, the ``[eos]`` section is skipped.
    """
    name    = material.get("name") or material.get("formula", "unknown")
    formula = material.get("formula", "")
    today   = datetime.date.today().isoformat()

    lines: List[str] = []

    # ── File header ────────────────────────────────────────────────────
    lines += [
        f"# EoS Material File — {name} ({formula})",
        f"# Generated by Dioptas / EoS Database  •  {today}",
    ]
    if eos and eos.get("reference"):
        lines.append(f"# EoS reference: {eos['reference']}")
    lines += ["", ""]

    # ── [material] ─────────────────────────────────────────────────────
    lines.append("[material]")
    lines.append(f'name     = {_toml_str(name)}')
    lines.append(f'formula  = {_toml_str(formula)}')
    lines.append(f'symmetry = {_toml_str(material.get("symmetry", ""))}')
    lines.append("")

    # Lattice parameters with inline comments
    a = material.get("a"); b = material.get("b"); c = material.get("c")
    lines.append(f"a = {_toml_num(a)}   # Å — lattice parameter a")
    lines.append(f"b = {_toml_num(b)}   # Å — lattice parameter b")
    lines.append(f"c = {_toml_num(c)}   # Å — lattice parameter c")
    lines.append(f'alpha = {_toml_num(material.get("alpha"))}   # °')
    lines.append(f'beta  = {_toml_num(material.get("beta"))}    # °')
    lines.append(f'gamma = {_toml_num(material.get("gamma"))}   # °')

    if material.get("notes"):
        lines.append(f'notes = {_toml_str(material["notes"])}')

    lines += ["", ""]

    # ── [eos] ──────────────────────────────────────────────────────────
    if eos:
        lines.append("[eos]")
        lines.append(f'type      = {_toml_str(eos.get("eos_type", ""))}   # BM2 | BM3 | BM4 | Vinet | Holzapfel')
        if eos.get("eos_order"):
            lines.append(f'order     = {eos["eos_order"]}   # for Birch-Murnaghan')
        lines.append(f'reference = {_toml_str(eos.get("reference") or "")}')
        lines.append("")

        v0   = eos.get("v0");        k0   = eos.get("k0")
        k0p  = eos.get("k0_prime");  a0   = eos.get("alpha0")
        dkdt = eos.get("dK_dT");     tref = eos.get("reference_temperature")

        lines.append(f"v0       = {_toml_num(v0)}   # Å³ — zero-pressure volume")
        lines.append(f"k0       = {_toml_num(k0)}   # GPa — zero-pressure bulk modulus")
        lines.append(f"k0_prime = {_toml_num(k0p)}  # dK/dP (dimensionless)")
        if a0 is not None:
            lines.append(f"alpha_t  = {_toml_num(a0)}  # K⁻¹ — thermal expansion coefficient")
        if dkdt is not None:
            lines.append(f"dK_dT    = {_toml_num(dkdt)}  # GPa K⁻¹ — temperature derivative of K0")
        if tref is not None:
            lines.append(f"t_ref    = {_toml_num(tref)}  # K — reference temperature")

        if eos.get("notes"):
            lines.append(f'notes    = {_toml_str(eos["notes"])}')

        if eos.get("pressure_range_min") is not None:
            lines.append(
                f"pressure_range = [{_toml_num(eos['pressure_range_min'])}, "
                f"{_toml_num(eos['pressure_range_max'])}]  # GPa"
            )

        lines += ["", ""]

    # ── [[peaks]] ──────────────────────────────────────────────────────
    peaks = material.get("diffraction_peaks", [])
    if peaks:
        lines.append("# Diffraction peaks — Miller indices, d-spacing (Å), relative intensity")
        for pk in peaks:
            h = pk.get("h", 0); k = pk.get("k", 0); l = pk.get("l", 0)
            d = pk.get("d_spacing", 0); I = pk.get("intensity", 0)
            lines.append("[[peaks]]")
            lines.append(
                f"h = {h}; k = {k}; l = {l};  "
                f"d = {float(d):.4f}; intensity = {float(I):.1f}"
            )

    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _toml_str(value) -> str:
    """Wrap a Python value as a TOML inline string."""
    return f'"{value}"' if value is not None else '""'


def _toml_num(value) -> str:
    """Format a numeric value for TOML (handles None gracefully)."""
    if value is None:
        return "null"
    try:
        f = float(value)
        # Prefer compact notation for very small/large numbers
        if f != 0 and (abs(f) < 1e-3 or abs(f) >= 1e6):
            return f"{f:.6e}"
        return f"{f}"
    except (TypeError, ValueError):
        return str(value)
