# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'XrsCalibration.ui'
#
# Created: Mon Apr 14 15:33:27 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8

    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_XrsCalibrationWidget(object):
    def setupUi(self, XrsCalibrationWidget):
        XrsCalibrationWidget.setObjectName(_fromUtf8("XrsCalibrationWidget"))
        XrsCalibrationWidget.resize(954, 598)
        self.horizontalLayout_3 = QtGui.QHBoxLayout(XrsCalibrationWidget)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.splitter = QtGui.QSplitter(XrsCalibrationWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.load_file_btn = QtGui.QPushButton(self.layoutWidget)
        self.load_file_btn.setObjectName(_fromUtf8("load_file_btn"))
        self.horizontalLayout_2.addWidget(self.load_file_btn)
        self.cake_btn = QtGui.QPushButton(self.layoutWidget)
        self.cake_btn.setObjectName(_fromUtf8("cake_btn"))
        self.horizontalLayout_2.addWidget(self.cake_btn)
        self.spectrum_btn = QtGui.QPushButton(self.layoutWidget)
        self.spectrum_btn.setObjectName(_fromUtf8("spectrum_btn"))
        self.horizontalLayout_2.addWidget(self.spectrum_btn)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.graphicsView = QtGui.QGraphicsView(self.layoutWidget)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.verticalLayout_5.addWidget(self.graphicsView)
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.f2_distance_txt = QtGui.QToolBox(self.layoutWidget1)
        self.f2_distance_txt.setObjectName(_fromUtf8("f2_distance_txt"))
        self.toolBoxPage1 = QtGui.QWidget()
        self.toolBoxPage1.setGeometry(QtCore.QRect(0, 0, 465, 418))
        self.toolBoxPage1.setObjectName(_fromUtf8("toolBoxPage1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.toolBoxPage1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.toolBoxPage1)
        self.label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.sv_distance_txt = QtGui.QLineEdit(self.toolBoxPage1)
        self.sv_distance_txt.setObjectName(_fromUtf8("sv_distance_txt"))
        self.gridLayout.addWidget(self.sv_distance_txt, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.toolBoxPage1)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.toolBoxPage1)
        self.label_2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.sv_wavelength_txt = QtGui.QLineEdit(self.toolBoxPage1)
        self.sv_wavelength_txt.setObjectName(_fromUtf8("sv_wavelength_txt"))
        self.gridLayout.addWidget(self.sv_wavelength_txt, 1, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.toolBoxPage1)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.toolBoxPage1)
        self.label_3.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.sv_pixel_width_txt = QtGui.QLineEdit(self.toolBoxPage1)
        self.sv_pixel_width_txt.setObjectName(_fromUtf8("sv_pixel_width_txt"))
        self.gridLayout.addWidget(self.sv_pixel_width_txt, 2, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.toolBoxPage1)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 2, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.toolBoxPage1)
        self.label_4.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.sv_pixel_height_txt = QtGui.QLineEdit(self.toolBoxPage1)
        self.sv_pixel_height_txt.setObjectName(_fromUtf8("sv_pixel_height_txt"))
        self.gridLayout.addWidget(self.sv_pixel_height_txt, 3, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.toolBoxPage1)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 3, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.toolBoxPage1)
        self.label_5.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.calibrant_cb = QtGui.QComboBox(self.toolBoxPage1)
        self.calibrant_cb.setEditable(False)
        self.calibrant_cb.setFrame(True)
        self.calibrant_cb.setObjectName(_fromUtf8("calibrant_cb"))
        self.gridLayout.addWidget(self.calibrant_cb, 4, 1, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.rotate_p90_btn = QtGui.QPushButton(self.toolBoxPage1)
        self.rotate_p90_btn.setObjectName(_fromUtf8("rotate_p90_btn"))
        self.verticalLayout.addWidget(self.rotate_p90_btn)
        self.rotate_m90_btn = QtGui.QPushButton(self.toolBoxPage1)
        self.rotate_m90_btn.setObjectName(_fromUtf8("rotate_m90_btn"))
        self.verticalLayout.addWidget(self.rotate_m90_btn)
        self.invert_horizontal_btn = QtGui.QPushButton(self.toolBoxPage1)
        self.invert_horizontal_btn.setObjectName(_fromUtf8("invert_horizontal_btn"))
        self.verticalLayout.addWidget(self.invert_horizontal_btn)
        self.invert_vertical_btn = QtGui.QPushButton(self.toolBoxPage1)
        self.invert_vertical_btn.setObjectName(_fromUtf8("invert_vertical_btn"))
        self.verticalLayout.addWidget(self.invert_vertical_btn)
        spacerItem = QtGui.QSpacerItem(20, 178, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.f2_distance_txt.addItem(self.toolBoxPage1, _fromUtf8(""))
        self.pyFAI = QtGui.QWidget()
        self.pyFAI.setGeometry(QtCore.QRect(0, 0, 465, 418))
        self.pyFAI.setObjectName(_fromUtf8("pyFAI"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.pyFAI)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_25 = QtGui.QLabel(self.pyFAI)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_2.addWidget(self.label_25, 3, 2, 1, 1)
        self.label_21 = QtGui.QLabel(self.pyFAI)
        self.label_21.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_2.addWidget(self.label_21, 0, 0, 1, 1)
        self.label_30 = QtGui.QLabel(self.pyFAI)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_2.addWidget(self.label_30, 5, 2, 1, 1)
        self.label_23 = QtGui.QLabel(self.pyFAI)
        self.label_23.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_2.addWidget(self.label_23, 2, 0, 1, 1)
        self.pf_center_y_txt = QtGui.QLineEdit(self.pyFAI)
        self.pf_center_y_txt.setObjectName(_fromUtf8("pf_center_y_txt"))
        self.gridLayout_2.addWidget(self.pf_center_y_txt, 3, 1, 1, 1)
        self.label_28 = QtGui.QLabel(self.pyFAI)
        self.label_28.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_2.addWidget(self.label_28, 6, 0, 1, 1)
        self.label_33 = QtGui.QLabel(self.pyFAI)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_2.addWidget(self.label_33, 8, 2, 1, 1)
        self.label_32 = QtGui.QLabel(self.pyFAI)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_2.addWidget(self.label_32, 7, 2, 1, 1)
        self.pf_poni2_txt = QtGui.QLineEdit(self.pyFAI)
        self.pf_poni2_txt.setObjectName(_fromUtf8("pf_poni2_txt"))
        self.gridLayout_2.addWidget(self.pf_poni2_txt, 5, 1, 1, 1)
        self.label_26 = QtGui.QLabel(self.pyFAI)
        self.label_26.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_2.addWidget(self.label_26, 3, 0, 1, 1)
        self.label_29 = QtGui.QLabel(self.pyFAI)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_2.addWidget(self.label_29, 4, 2, 1, 1)
        self.pf_rotation3_txt = QtGui.QLineEdit(self.pyFAI)
        self.pf_rotation3_txt.setObjectName(_fromUtf8("pf_rotation3_txt"))
        self.gridLayout_2.addWidget(self.pf_rotation3_txt, 8, 1, 1, 1)
        self.pf_rotation1_txt = QtGui.QLineEdit(self.pyFAI)
        self.pf_rotation1_txt.setObjectName(_fromUtf8("pf_rotation1_txt"))
        self.gridLayout_2.addWidget(self.pf_rotation1_txt, 6, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.pyFAI)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_2.addWidget(self.label_19, 1, 2, 1, 1)
        self.label_31 = QtGui.QLabel(self.pyFAI)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_2.addWidget(self.label_31, 6, 2, 1, 1)
        self.label_24 = QtGui.QLabel(self.pyFAI)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_2.addWidget(self.label_24, 2, 2, 1, 1)
        self.pf_rotation2_txt = QtGui.QLineEdit(self.pyFAI)
        self.pf_rotation2_txt.setObjectName(_fromUtf8("pf_rotation2_txt"))
        self.gridLayout_2.addWidget(self.pf_rotation2_txt, 7, 1, 1, 1)
        self.pf_distance_txt = QtGui.QLineEdit(self.pyFAI)
        self.pf_distance_txt.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pf_distance_txt.setObjectName(_fromUtf8("pf_distance_txt"))
        self.gridLayout_2.addWidget(self.pf_distance_txt, 0, 1, 1, 1)
        self.pf_center_x_txt = QtGui.QLineEdit(self.pyFAI)
        self.pf_center_x_txt.setObjectName(_fromUtf8("pf_center_x_txt"))
        self.gridLayout_2.addWidget(self.pf_center_x_txt, 2, 1, 1, 1)
        self.pf_poni1_txt = QtGui.QLineEdit(self.pyFAI)
        self.pf_poni1_txt.setObjectName(_fromUtf8("pf_poni1_txt"))
        self.gridLayout_2.addWidget(self.pf_poni1_txt, 4, 1, 1, 1)
        self.pf_distance_cb = QtGui.QCheckBox(self.pyFAI)
        self.pf_distance_cb.setText(_fromUtf8(""))
        self.pf_distance_cb.setChecked(True)
        self.pf_distance_cb.setObjectName(_fromUtf8("pf_distance_cb"))
        self.gridLayout_2.addWidget(self.pf_distance_cb, 0, 3, 1, 1)
        self.label_27 = QtGui.QLabel(self.pyFAI)
        self.label_27.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_2.addWidget(self.label_27, 4, 0, 1, 1)
        self.pf_wavelength_txt = QtGui.QLineEdit(self.pyFAI)
        self.pf_wavelength_txt.setObjectName(_fromUtf8("pf_wavelength_txt"))
        self.gridLayout_2.addWidget(self.pf_wavelength_txt, 1, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.pyFAI)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_2.addWidget(self.label_20, 0, 2, 1, 1)
        self.label_22 = QtGui.QLabel(self.pyFAI)
        self.label_22.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_2.addWidget(self.label_22, 1, 0, 1, 1)
        self.pf_wavelength_cb = QtGui.QCheckBox(self.pyFAI)
        self.pf_wavelength_cb.setText(_fromUtf8(""))
        self.pf_wavelength_cb.setObjectName(_fromUtf8("pf_wavelength_cb"))
        self.gridLayout_2.addWidget(self.pf_wavelength_cb, 1, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        spacerItem1 = QtGui.QSpacerItem(20, 54, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.f2_distance_txt.addItem(self.pyFAI, _fromUtf8(""))
        self.toolBoxPage3 = QtGui.QWidget()
        self.toolBoxPage3.setGeometry(QtCore.QRect(0, 0, 465, 418))
        self.toolBoxPage3.setObjectName(_fromUtf8("toolBoxPage3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.toolBoxPage3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_38 = QtGui.QLabel(self.toolBoxPage3)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_3.addWidget(self.label_38, 1, 2, 1, 1)
        self.f2_center_x_txt = QtGui.QLineEdit(self.toolBoxPage3)
        self.f2_center_x_txt.setObjectName(_fromUtf8("f2_center_x_txt"))
        self.gridLayout_3.addWidget(self.f2_center_x_txt, 2, 1, 1, 1)
        self.f2_wavelength_txt = QtGui.QLineEdit(self.toolBoxPage3)
        self.f2_wavelength_txt.setObjectName(_fromUtf8("f2_wavelength_txt"))
        self.gridLayout_3.addWidget(self.f2_wavelength_txt, 1, 1, 1, 1)
        self.label_45 = QtGui.QLabel(self.toolBoxPage3)
        self.label_45.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_3.addWidget(self.label_45, 5, 0, 1, 1)
        self.label_37 = QtGui.QLabel(self.toolBoxPage3)
        self.label_37.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_3.addWidget(self.label_37, 0, 0, 1, 1)
        self.f2_center_y_txt = QtGui.QLineEdit(self.toolBoxPage3)
        self.f2_center_y_txt.setObjectName(_fromUtf8("f2_center_y_txt"))
        self.gridLayout_3.addWidget(self.f2_center_y_txt, 3, 1, 1, 1)
        self.f2_rotation_txt = QtGui.QLineEdit(self.toolBoxPage3)
        self.f2_rotation_txt.setObjectName(_fromUtf8("f2_rotation_txt"))
        self.gridLayout_3.addWidget(self.f2_rotation_txt, 5, 1, 1, 1)
        self.label_36 = QtGui.QLabel(self.toolBoxPage3)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_3.addWidget(self.label_36, 0, 2, 1, 1)
        self.label_40 = QtGui.QLabel(self.toolBoxPage3)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_3.addWidget(self.label_40, 3, 2, 1, 1)
        self.label_44 = QtGui.QLabel(self.toolBoxPage3)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_3.addWidget(self.label_44, 5, 2, 1, 1)
        self.label_35 = QtGui.QLabel(self.toolBoxPage3)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_3.addWidget(self.label_35, 2, 2, 1, 1)
        self.label_41 = QtGui.QLabel(self.toolBoxPage3)
        self.label_41.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_3.addWidget(self.label_41, 3, 0, 1, 1)
        self.label_43 = QtGui.QLabel(self.toolBoxPage3)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_3.addWidget(self.label_43, 4, 2, 1, 1)
        self.label_39 = QtGui.QLabel(self.toolBoxPage3)
        self.label_39.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_3.addWidget(self.label_39, 2, 0, 1, 1)
        self.label_34 = QtGui.QLabel(self.toolBoxPage3)
        self.label_34.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_3.addWidget(self.label_34, 1, 0, 1, 1)
        self.f2_wavelength_cb = QtGui.QCheckBox(self.toolBoxPage3)
        self.f2_wavelength_cb.setText(_fromUtf8(""))
        self.f2_wavelength_cb.setObjectName(_fromUtf8("f2_wavelength_cb"))
        self.gridLayout_3.addWidget(self.f2_wavelength_cb, 1, 3, 1, 1)
        self.lineEdit_21 = QtGui.QLineEdit(self.toolBoxPage3)
        self.lineEdit_21.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.gridLayout_3.addWidget(self.lineEdit_21, 0, 1, 1, 1)
        self.label_42 = QtGui.QLabel(self.toolBoxPage3)
        self.label_42.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_3.addWidget(self.label_42, 4, 0, 1, 1)
        self.f2_distance_cb = QtGui.QCheckBox(self.toolBoxPage3)
        self.f2_distance_cb.setText(_fromUtf8(""))
        self.f2_distance_cb.setChecked(True)
        self.f2_distance_cb.setObjectName(_fromUtf8("f2_distance_cb"))
        self.gridLayout_3.addWidget(self.f2_distance_cb, 0, 3, 1, 1)
        self.f2_tilt_txt = QtGui.QLineEdit(self.toolBoxPage3)
        self.f2_tilt_txt.setObjectName(_fromUtf8("f2_tilt_txt"))
        self.gridLayout_3.addWidget(self.f2_tilt_txt, 4, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        spacerItem2 = QtGui.QSpacerItem(20, 147, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.f2_distance_txt.addItem(self.toolBoxPage3, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.f2_distance_txt)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.load_calibration_btn = QtGui.QPushButton(self.layoutWidget1)
        self.load_calibration_btn.setObjectName(_fromUtf8("load_calibration_btn"))
        self.horizontalLayout.addWidget(self.load_calibration_btn)
        self.save_calibration_btn = QtGui.QPushButton(self.layoutWidget1)
        self.save_calibration_btn.setObjectName(_fromUtf8("save_calibration_btn"))
        self.horizontalLayout.addWidget(self.save_calibration_btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_4.setStretch(0, 10)
        self.verticalLayout_4.setStretch(1, 1)
        self.horizontalLayout_3.addWidget(self.splitter)

        self.retranslateUi(XrsCalibrationWidget)
        QtCore.QObject.connect(self.f2_distance_cb, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pf_distance_cb.toggle)
        QtCore.QObject.connect(self.pf_distance_cb, QtCore.SIGNAL(_fromUtf8("clicked()")), self.f2_distance_cb.toggle)
        QtCore.QObject.connect(self.f2_wavelength_cb, QtCore.SIGNAL(_fromUtf8("clicked()")),
                               self.pf_wavelength_cb.toggle)
        QtCore.QObject.connect(self.pf_wavelength_cb, QtCore.SIGNAL(_fromUtf8("clicked()")),
                               self.f2_wavelength_cb.toggle)
        QtCore.QMetaObject.connectSlotsByName(XrsCalibrationWidget)
        XrsCalibrationWidget.setTabOrder(self.load_file_btn, self.sv_distance_txt)
        XrsCalibrationWidget.setTabOrder(self.sv_distance_txt, self.sv_wavelength_txt)
        XrsCalibrationWidget.setTabOrder(self.sv_wavelength_txt, self.sv_pixel_width_txt)
        XrsCalibrationWidget.setTabOrder(self.sv_pixel_width_txt, self.sv_pixel_height_txt)
        XrsCalibrationWidget.setTabOrder(self.sv_pixel_height_txt, self.calibrant_cb)
        XrsCalibrationWidget.setTabOrder(self.calibrant_cb, self.rotate_p90_btn)
        XrsCalibrationWidget.setTabOrder(self.rotate_p90_btn, self.rotate_m90_btn)
        XrsCalibrationWidget.setTabOrder(self.rotate_m90_btn, self.invert_horizontal_btn)
        XrsCalibrationWidget.setTabOrder(self.invert_horizontal_btn, self.invert_vertical_btn)
        XrsCalibrationWidget.setTabOrder(self.invert_vertical_btn, self.pf_distance_txt)
        XrsCalibrationWidget.setTabOrder(self.pf_distance_txt, self.pf_distance_cb)
        XrsCalibrationWidget.setTabOrder(self.pf_distance_cb, self.pf_wavelength_txt)
        XrsCalibrationWidget.setTabOrder(self.pf_wavelength_txt, self.pf_wavelength_cb)
        XrsCalibrationWidget.setTabOrder(self.pf_wavelength_cb, self.pf_center_x_txt)
        XrsCalibrationWidget.setTabOrder(self.pf_center_x_txt, self.pf_center_y_txt)
        XrsCalibrationWidget.setTabOrder(self.pf_center_y_txt, self.pf_poni1_txt)
        XrsCalibrationWidget.setTabOrder(self.pf_poni1_txt, self.pf_poni2_txt)
        XrsCalibrationWidget.setTabOrder(self.pf_poni2_txt, self.pf_rotation1_txt)
        XrsCalibrationWidget.setTabOrder(self.pf_rotation1_txt, self.pf_rotation2_txt)
        XrsCalibrationWidget.setTabOrder(self.pf_rotation2_txt, self.pf_rotation3_txt)
        XrsCalibrationWidget.setTabOrder(self.pf_rotation3_txt, self.lineEdit_21)
        XrsCalibrationWidget.setTabOrder(self.lineEdit_21, self.f2_distance_cb)
        XrsCalibrationWidget.setTabOrder(self.f2_distance_cb, self.f2_wavelength_txt)
        XrsCalibrationWidget.setTabOrder(self.f2_wavelength_txt, self.f2_wavelength_cb)
        XrsCalibrationWidget.setTabOrder(self.f2_wavelength_cb, self.f2_center_x_txt)
        XrsCalibrationWidget.setTabOrder(self.f2_center_x_txt, self.f2_center_y_txt)
        XrsCalibrationWidget.setTabOrder(self.f2_center_y_txt, self.f2_tilt_txt)
        XrsCalibrationWidget.setTabOrder(self.f2_tilt_txt, self.f2_rotation_txt)
        XrsCalibrationWidget.setTabOrder(self.f2_rotation_txt, self.cake_btn)
        XrsCalibrationWidget.setTabOrder(self.cake_btn, self.spectrum_btn)
        XrsCalibrationWidget.setTabOrder(self.spectrum_btn, self.load_calibration_btn)
        XrsCalibrationWidget.setTabOrder(self.load_calibration_btn, self.save_calibration_btn)
        XrsCalibrationWidget.setTabOrder(self.save_calibration_btn, self.graphicsView)

    def retranslateUi(self, XrsCalibrationWidget):
        XrsCalibrationWidget.setWindowTitle(_translate("XrsCalibrationWidget", "Form", None))
        self.load_file_btn.setText(_translate("XrsCalibrationWidget", "Load File", None))
        self.cake_btn.setText(_translate("XrsCalibrationWidget", "Cake", None))
        self.spectrum_btn.setText(_translate("XrsCalibrationWidget", "Spectrum", None))
        self.label.setText(_translate("XrsCalibrationWidget", "Distance:", None))
        self.label_6.setText(_translate("XrsCalibrationWidget", "mm", None))
        self.label_2.setText(_translate("XrsCalibrationWidget", "Wavelength:", None))
        self.label_7.setText(_translate("XrsCalibrationWidget", "A", None))
        self.label_3.setText(_translate("XrsCalibrationWidget", "Pixelwidth:", None))
        self.label_8.setText(_translate("XrsCalibrationWidget", "um", None))
        self.label_4.setText(_translate("XrsCalibrationWidget", "Pixelheight:", None))
        self.label_9.setText(_translate("XrsCalibrationWidget", "um", None))
        self.label_5.setText(_translate("XrsCalibrationWidget", "Calibrant:", None))
        self.rotate_p90_btn.setText(_translate("XrsCalibrationWidget", "Rotate +90 Deg", None))
        self.rotate_m90_btn.setText(_translate("XrsCalibrationWidget", "Rotate -90 Deg", None))
        self.invert_horizontal_btn.setText(_translate("XrsCalibrationWidget", "Invert horizontal", None))
        self.invert_vertical_btn.setText(_translate("XrsCalibrationWidget", "Invert vertical", None))
        self.f2_distance_txt.setItemText(self.f2_distance_txt.indexOf(self.toolBoxPage1),
                                         _translate("XrsCalibrationWidget", "Start Values", None))
        self.label_25.setText(_translate("XrsCalibrationWidget", "px", None))
        self.label_21.setText(_translate("XrsCalibrationWidget", "Distance:", None))
        self.label_30.setText(_translate("XrsCalibrationWidget", "m", None))
        self.label_23.setText(_translate("XrsCalibrationWidget", "Center X:", None))
        self.label_28.setText(_translate("XrsCalibrationWidget", "Rotations:", None))
        self.label_33.setText(_translate("XrsCalibrationWidget", "rad", None))
        self.label_32.setText(_translate("XrsCalibrationWidget", "rad", None))
        self.label_26.setText(_translate("XrsCalibrationWidget", "Center Y:", None))
        self.label_29.setText(_translate("XrsCalibrationWidget", "m", None))
        self.label_19.setText(_translate("XrsCalibrationWidget", "A", None))
        self.label_31.setText(_translate("XrsCalibrationWidget", "rad", None))
        self.label_24.setText(_translate("XrsCalibrationWidget", "px", None))
        self.label_27.setText(_translate("XrsCalibrationWidget", "PONI:", None))
        self.label_20.setText(_translate("XrsCalibrationWidget", "mm", None))
        self.label_22.setText(_translate("XrsCalibrationWidget", "Wavelength:", None))
        self.f2_distance_txt.setItemText(self.f2_distance_txt.indexOf(self.pyFAI),
                                         _translate("XrsCalibrationWidget", "pyFAI Calibration", None))
        self.label_38.setText(_translate("XrsCalibrationWidget", "A", None))
        self.label_45.setText(_translate("XrsCalibrationWidget", "Rotation:", None))
        self.label_37.setText(_translate("XrsCalibrationWidget", "Distance:", None))
        self.label_36.setText(_translate("XrsCalibrationWidget", "mm", None))
        self.label_40.setText(_translate("XrsCalibrationWidget", "px", None))
        self.label_44.setText(_translate("XrsCalibrationWidget", "deg", None))
        self.label_35.setText(_translate("XrsCalibrationWidget", "px", None))
        self.label_41.setText(_translate("XrsCalibrationWidget", "Center Y:", None))
        self.label_43.setText(_translate("XrsCalibrationWidget", "deg", None))
        self.label_39.setText(_translate("XrsCalibrationWidget", "Center X:", None))
        self.label_34.setText(_translate("XrsCalibrationWidget", "Wavelength:", None))
        self.label_42.setText(_translate("XrsCalibrationWidget", "Tilt:", None))
        self.f2_distance_txt.setItemText(self.f2_distance_txt.indexOf(self.toolBoxPage3),
                                         _translate("XrsCalibrationWidget", "Fit2D Calibration", None))
        self.load_calibration_btn.setText(_translate("XrsCalibrationWidget", "Load Calibration", None))
        self.save_calibration_btn.setText(_translate("XrsCalibrationWidget", "Save Calibration", None))

