#!/usr/bin/env python
import sys
from dioptas import main, icons_path, make_shortcut

if len(sys.argv) > 1 and sys.argv[1].startswith('makeshortcut'):
    make_shortcut('Dioptas', 'dioptas', description='Dioptas 2D XRD',
                  icon_path=icons_path, icon='icon')
else:
    main()
